// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "Conv_Accel_conv_hw_24_3_10_5_20_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st1_fsm_0 = "1";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st2_fsm_1 = "10";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st3_fsm_2 = "100";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st4_fsm_3 = "1000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st5_fsm_4 = "10000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st6_fsm_5 = "100000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<21> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv1_1 = "1";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_1 = "1";
const sc_lv<1> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv1_0 = "0";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_2 = "10";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_3 = "11";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_5 = "101";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_6 = "110";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_7 = "111";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_8 = "1000";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_9 = "1001";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_A = "1010";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_E = "1110";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_13 = "10011";
const sc_lv<4> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv4_0 = "0000";
const sc_lv<5> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv5_0 = "00000";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_4 = "100";
const sc_lv<2> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv2_0 = "00";
const sc_lv<3> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv3_0 = "000";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_14 = "10100";
const sc_lv<32> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv32_D = "1101";
const sc_lv<4> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv4_A = "1010";
const sc_lv<4> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv4_1 = "1";
const sc_lv<5> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv5_14 = "10100";
const sc_lv<5> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv5_1 = "1";
const sc_lv<2> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv2_3 = "11";
const sc_lv<2> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv2_1 = "1";
const sc_lv<3> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv3_5 = "101";
const sc_lv<3> Conv_Accel_conv_hw_24_3_10_5_20_s::ap_const_lv3_1 = "1";

Conv_Accel_conv_hw_24_3_10_5_20_s::Conv_Accel_conv_hw_24_3_10_5_20_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0 = new Conv_Accel_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0");
    Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0->clk(ap_clk);
    Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0->reset(ap_rst);
    Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0->din0(feature_map_load_reg_852);
    Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0->din1(tmp_28_reg_847);
    Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0->ce(grp_fu_218_ce);
    Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0->dout(grp_fu_218_p2);
    Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1 = new Conv_Accel_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1");
    Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1->clk(ap_clk);
    Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1->reset(ap_rst);
    Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1->din0(filter_q0);
    Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1->din1(image_r_q0);
    Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1->ce(grp_fu_222_ce);
    Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1->dout(grp_fu_222_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond5_fu_347_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond5_fu_347_p2 );

    SC_METHOD(thread_ap_sig_bdd_108);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_122);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_138);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_154);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_168);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_182);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_198);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_223);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_233);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_255);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_288);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_301);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_77);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_94);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_182 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_198 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_301 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_bdd_223 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_39 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_bdd_233 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_bdd_288 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_77 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_94 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_108 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_255 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_122 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_138 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_154 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_168 );

    SC_METHOD(thread_bias_address0);
    sensitive << ( bias_addr_reg_708 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_bias_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ch_3_fu_413_p2);
    sensitive << ( ch_reg_161 );

    SC_METHOD(thread_exitcond1_fu_561_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( lt_i_reg_196 );

    SC_METHOD(thread_exitcond2_fu_531_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( j3_reg_184 );

    SC_METHOD(thread_exitcond3_fu_484_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( i2_reg_172 );

    SC_METHOD(thread_exitcond4_fu_407_p2);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ch_reg_161 );

    SC_METHOD(thread_exitcond5_fu_347_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( filt1_reg_150 );

    SC_METHOD(thread_exitcond6_fu_322_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( j_reg_139 );

    SC_METHOD(thread_exitcond7_fu_275_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( i_reg_128 );

    SC_METHOD(thread_exitcond8_fu_228_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( filt_reg_117 );

    SC_METHOD(thread_exitcond_fu_649_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( lt_j_reg_207 );

    SC_METHOD(thread_feature_map_address0);
    sensitive << ( feature_map_addr_1_reg_796 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( tmp_63_cast_fu_343_p1 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_feature_map_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_feature_map_d0);
    sensitive << ( bias_q0 );
    sensitive << ( tmp_29_reg_857 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );

    SC_METHOD(thread_feature_map_we0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );

    SC_METHOD(thread_filt_4_fu_234_p2);
    sensitive << ( filt_reg_117 );

    SC_METHOD(thread_filt_5_fu_353_p2);
    sensitive << ( filt1_reg_150 );

    SC_METHOD(thread_filter_address0);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_76_cast_fu_670_p1 );

    SC_METHOD(thread_filter_ce0);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_grp_fu_218_ce);

    SC_METHOD(thread_grp_fu_222_ce);

    SC_METHOD(thread_i_4_fu_281_p2);
    sensitive << ( i_reg_128 );

    SC_METHOD(thread_i_5_fu_490_p2);
    sensitive << ( i2_reg_172 );

    SC_METHOD(thread_image_r_address0);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_77_cast_fu_690_p1 );

    SC_METHOD(thread_image_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_j_4_fu_328_p2);
    sensitive << ( j_reg_139 );

    SC_METHOD(thread_j_5_fu_537_p2);
    sensitive << ( j3_reg_184 );

    SC_METHOD(thread_lt_i_1_fu_567_p2);
    sensitive << ( lt_i_reg_196 );

    SC_METHOD(thread_lt_i_cast4_fu_557_p1);
    sensitive << ( lt_i_reg_196 );

    SC_METHOD(thread_lt_j_1_fu_655_p2);
    sensitive << ( lt_j_reg_207 );

    SC_METHOD(thread_lt_j_cast2_fu_645_p1);
    sensitive << ( lt_j_reg_207 );

    SC_METHOD(thread_p_shl10_cast_fu_505_p3);
    sensitive << ( tmp_51_fu_500_p2 );

    SC_METHOD(thread_p_shl11_cast_fu_521_p1);
    sensitive << ( tmp_52_fu_513_p3 );

    SC_METHOD(thread_p_shl12_cast_fu_623_p3);
    sensitive << ( tmp_60_fu_619_p1 );

    SC_METHOD(thread_p_shl13_cast_fu_631_p3);
    sensitive << ( tmp_59_fu_614_p2 );

    SC_METHOD(thread_p_shl14_cast_fu_596_p3);
    sensitive << ( tmp_57_fu_592_p1 );

    SC_METHOD(thread_p_shl1_cast_fu_265_p1);
    sensitive << ( tmp_37_fu_257_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_296_p3);
    sensitive << ( tmp_43_fu_291_p2 );

    SC_METHOD(thread_p_shl3_cast_fu_312_p1);
    sensitive << ( tmp_35_fu_304_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_397_p1);
    sensitive << ( tmp_41_fu_389_p3 );

    SC_METHOD(thread_p_shl6_cast1_fu_371_p1);
    sensitive << ( tmp_39_fu_363_p3 );

    SC_METHOD(thread_p_shl6_cast_fu_375_p1);
    sensitive << ( tmp_39_fu_363_p3 );

    SC_METHOD(thread_p_shl7_fu_474_p1);
    sensitive << ( tmp_36_fu_466_p3 );

    SC_METHOD(thread_p_shl8_cast_fu_431_p1);
    sensitive << ( tmp_45_fu_423_p3 );

    SC_METHOD(thread_p_shl9_cast_fu_443_p1);
    sensitive << ( tmp_46_fu_435_p3 );

    SC_METHOD(thread_p_shl_cast_fu_253_p1);
    sensitive << ( tmp_s_fu_245_p3 );

    SC_METHOD(thread_tmp_17_cast_fu_287_p1);
    sensitive << ( i_reg_128 );

    SC_METHOD(thread_tmp_18_cast_fu_419_p1);
    sensitive << ( ch_reg_161 );

    SC_METHOD(thread_tmp_19_cast_fu_334_p1);
    sensitive << ( j_reg_139 );

    SC_METHOD(thread_tmp_20_cast_fu_496_p1);
    sensitive << ( i2_reg_172 );

    SC_METHOD(thread_tmp_21_cast_fu_543_p1);
    sensitive << ( j3_reg_184 );

    SC_METHOD(thread_tmp_22_fu_573_p2);
    sensitive << ( i2_reg_172 );
    sensitive << ( lt_i_cast4_fu_557_p1 );

    SC_METHOD(thread_tmp_23_fu_579_p1);
    sensitive << ( lt_i_reg_196 );

    SC_METHOD(thread_tmp_24_cast_fu_610_p1);
    sensitive << ( tmp_22_fu_573_p2 );

    SC_METHOD(thread_tmp_25_cast_fu_661_p1);
    sensitive << ( lt_j_reg_207 );

    SC_METHOD(thread_tmp_26_fu_675_p2);
    sensitive << ( j3_reg_184 );
    sensitive << ( lt_j_cast2_fu_645_p1 );

    SC_METHOD(thread_tmp_27_cast_fu_681_p1);
    sensitive << ( tmp_26_fu_675_p2 );

    SC_METHOD(thread_tmp_35_fu_304_p3);
    sensitive << ( tmp_43_fu_291_p2 );

    SC_METHOD(thread_tmp_36_fu_466_p3);
    sensitive << ( tmp_48_fu_457_p2 );

    SC_METHOD(thread_tmp_37_fu_257_p3);
    sensitive << ( filt_reg_117 );

    SC_METHOD(thread_tmp_38_fu_269_p2);
    sensitive << ( p_shl1_cast_fu_265_p1 );
    sensitive << ( p_shl_cast_fu_253_p1 );

    SC_METHOD(thread_tmp_39_fu_363_p3);
    sensitive << ( filt1_reg_150 );

    SC_METHOD(thread_tmp_40_fu_379_p2);
    sensitive << ( p_shl6_cast_fu_375_p1 );
    sensitive << ( tmp_cast_fu_359_p1 );

    SC_METHOD(thread_tmp_41_fu_389_p3);
    sensitive << ( filt1_reg_150 );

    SC_METHOD(thread_tmp_42_fu_401_p2);
    sensitive << ( p_shl6_cast1_fu_371_p1 );
    sensitive << ( p_shl4_cast_fu_397_p1 );

    SC_METHOD(thread_tmp_43_fu_291_p2);
    sensitive << ( tmp_38_reg_703 );
    sensitive << ( tmp_17_cast_fu_287_p1 );

    SC_METHOD(thread_tmp_44_fu_316_p2);
    sensitive << ( p_shl2_cast_fu_296_p3 );
    sensitive << ( p_shl3_cast_fu_312_p1 );

    SC_METHOD(thread_tmp_45_fu_423_p3);
    sensitive << ( ch_reg_161 );

    SC_METHOD(thread_tmp_46_fu_435_p3);
    sensitive << ( ch_reg_161 );

    SC_METHOD(thread_tmp_47_fu_447_p2);
    sensitive << ( p_shl8_cast_fu_431_p1 );
    sensitive << ( p_shl9_cast_fu_443_p1 );

    SC_METHOD(thread_tmp_48_fu_457_p2);
    sensitive << ( tmp_49_cast_reg_747 );
    sensitive << ( tmp_18_cast_fu_419_p1 );

    SC_METHOD(thread_tmp_49_cast_fu_385_p1);
    sensitive << ( tmp_40_fu_379_p2 );

    SC_METHOD(thread_tmp_49_fu_478_p2);
    sensitive << ( tmp_60_cast_fu_462_p1 );
    sensitive << ( p_shl7_fu_474_p1 );

    SC_METHOD(thread_tmp_50_fu_338_p2);
    sensitive << ( tmp_44_reg_721 );
    sensitive << ( tmp_19_cast_fu_334_p1 );

    SC_METHOD(thread_tmp_51_fu_500_p2);
    sensitive << ( tmp_42_reg_752 );
    sensitive << ( tmp_20_cast_fu_496_p1 );

    SC_METHOD(thread_tmp_52_fu_513_p3);
    sensitive << ( tmp_51_fu_500_p2 );

    SC_METHOD(thread_tmp_53_fu_525_p2);
    sensitive << ( p_shl10_cast_fu_505_p3 );
    sensitive << ( p_shl11_cast_fu_521_p1 );

    SC_METHOD(thread_tmp_54_fu_547_p2);
    sensitive << ( tmp_53_reg_783 );
    sensitive << ( tmp_21_cast_fu_543_p1 );

    SC_METHOD(thread_tmp_55_fu_583_p2);
    sensitive << ( tmp_49_reg_770 );
    sensitive << ( tmp_23_fu_579_p1 );

    SC_METHOD(thread_tmp_56_fu_588_p1);
    sensitive << ( tmp_55_fu_583_p2 );

    SC_METHOD(thread_tmp_57_fu_592_p1);
    sensitive << ( tmp_55_fu_583_p2 );

    SC_METHOD(thread_tmp_58_fu_604_p2);
    sensitive << ( p_shl14_cast_fu_596_p3 );
    sensitive << ( tmp_56_fu_588_p1 );

    SC_METHOD(thread_tmp_59_cast_fu_453_p1);
    sensitive << ( tmp_47_fu_447_p2 );

    SC_METHOD(thread_tmp_59_fu_614_p2);
    sensitive << ( tmp_59_cast_reg_765 );
    sensitive << ( tmp_24_cast_fu_610_p1 );

    SC_METHOD(thread_tmp_60_cast_fu_462_p1);
    sensitive << ( tmp_48_fu_457_p2 );

    SC_METHOD(thread_tmp_60_fu_619_p1);
    sensitive << ( tmp_59_fu_614_p2 );

    SC_METHOD(thread_tmp_61_fu_639_p2);
    sensitive << ( p_shl12_cast_fu_623_p3 );
    sensitive << ( p_shl13_cast_fu_631_p3 );

    SC_METHOD(thread_tmp_62_fu_665_p2);
    sensitive << ( tmp_58_reg_809 );
    sensitive << ( tmp_25_cast_fu_661_p1 );

    SC_METHOD(thread_tmp_63_cast_fu_343_p1);
    sensitive << ( tmp_50_reg_734 );

    SC_METHOD(thread_tmp_63_fu_685_p2);
    sensitive << ( tmp_61_reg_814 );
    sensitive << ( tmp_27_cast_fu_681_p1 );

    SC_METHOD(thread_tmp_68_cast_fu_552_p1);
    sensitive << ( tmp_54_fu_547_p2 );

    SC_METHOD(thread_tmp_76_cast_fu_670_p1);
    sensitive << ( tmp_62_fu_665_p2 );

    SC_METHOD(thread_tmp_77_cast_fu_690_p1);
    sensitive << ( tmp_63_fu_685_p2 );

    SC_METHOD(thread_tmp_cast_fu_359_p1);
    sensitive << ( filt1_reg_150 );

    SC_METHOD(thread_tmp_fu_240_p1);
    sensitive << ( filt_reg_117 );

    SC_METHOD(thread_tmp_s_fu_245_p3);
    sensitive << ( filt_reg_117 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond8_fu_228_p2 );
    sensitive << ( exitcond7_fu_275_p2 );
    sensitive << ( exitcond6_fu_322_p2 );
    sensitive << ( exitcond5_fu_347_p2 );
    sensitive << ( exitcond4_fu_407_p2 );
    sensitive << ( exitcond3_fu_484_p2 );
    sensitive << ( exitcond2_fu_531_p2 );
    sensitive << ( exitcond1_fu_561_p2 );
    sensitive << ( exitcond_fu_649_p2 );

    ap_CS_fsm = "000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Conv_Accel_conv_hw_24_3_10_5_20_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, image_r_address0, "(port)image_r_address0");
    sc_trace(mVcdFile, image_r_ce0, "(port)image_r_ce0");
    sc_trace(mVcdFile, image_r_q0, "(port)image_r_q0");
    sc_trace(mVcdFile, filter_address0, "(port)filter_address0");
    sc_trace(mVcdFile, filter_ce0, "(port)filter_ce0");
    sc_trace(mVcdFile, filter_q0, "(port)filter_q0");
    sc_trace(mVcdFile, bias_address0, "(port)bias_address0");
    sc_trace(mVcdFile, bias_ce0, "(port)bias_ce0");
    sc_trace(mVcdFile, bias_q0, "(port)bias_q0");
    sc_trace(mVcdFile, feature_map_address0, "(port)feature_map_address0");
    sc_trace(mVcdFile, feature_map_ce0, "(port)feature_map_ce0");
    sc_trace(mVcdFile, feature_map_we0, "(port)feature_map_we0");
    sc_trace(mVcdFile, feature_map_d0, "(port)feature_map_d0");
    sc_trace(mVcdFile, feature_map_q0, "(port)feature_map_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_39, "ap_sig_bdd_39");
    sc_trace(mVcdFile, filt_4_fu_234_p2, "filt_4_fu_234_p2");
    sc_trace(mVcdFile, filt_4_reg_698, "filt_4_reg_698");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_77, "ap_sig_bdd_77");
    sc_trace(mVcdFile, tmp_38_fu_269_p2, "tmp_38_fu_269_p2");
    sc_trace(mVcdFile, tmp_38_reg_703, "tmp_38_reg_703");
    sc_trace(mVcdFile, exitcond8_fu_228_p2, "exitcond8_fu_228_p2");
    sc_trace(mVcdFile, bias_addr_reg_708, "bias_addr_reg_708");
    sc_trace(mVcdFile, i_4_fu_281_p2, "i_4_fu_281_p2");
    sc_trace(mVcdFile, i_4_reg_716, "i_4_reg_716");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_94, "ap_sig_bdd_94");
    sc_trace(mVcdFile, tmp_44_fu_316_p2, "tmp_44_fu_316_p2");
    sc_trace(mVcdFile, tmp_44_reg_721, "tmp_44_reg_721");
    sc_trace(mVcdFile, exitcond7_fu_275_p2, "exitcond7_fu_275_p2");
    sc_trace(mVcdFile, j_4_fu_328_p2, "j_4_fu_328_p2");
    sc_trace(mVcdFile, j_4_reg_729, "j_4_reg_729");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_108, "ap_sig_bdd_108");
    sc_trace(mVcdFile, tmp_50_fu_338_p2, "tmp_50_fu_338_p2");
    sc_trace(mVcdFile, tmp_50_reg_734, "tmp_50_reg_734");
    sc_trace(mVcdFile, exitcond6_fu_322_p2, "exitcond6_fu_322_p2");
    sc_trace(mVcdFile, filt_5_fu_353_p2, "filt_5_fu_353_p2");
    sc_trace(mVcdFile, filt_5_reg_742, "filt_5_reg_742");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_122, "ap_sig_bdd_122");
    sc_trace(mVcdFile, tmp_49_cast_fu_385_p1, "tmp_49_cast_fu_385_p1");
    sc_trace(mVcdFile, tmp_49_cast_reg_747, "tmp_49_cast_reg_747");
    sc_trace(mVcdFile, exitcond5_fu_347_p2, "exitcond5_fu_347_p2");
    sc_trace(mVcdFile, tmp_42_fu_401_p2, "tmp_42_fu_401_p2");
    sc_trace(mVcdFile, tmp_42_reg_752, "tmp_42_reg_752");
    sc_trace(mVcdFile, ch_3_fu_413_p2, "ch_3_fu_413_p2");
    sc_trace(mVcdFile, ch_3_reg_760, "ch_3_reg_760");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_138, "ap_sig_bdd_138");
    sc_trace(mVcdFile, tmp_59_cast_fu_453_p1, "tmp_59_cast_fu_453_p1");
    sc_trace(mVcdFile, tmp_59_cast_reg_765, "tmp_59_cast_reg_765");
    sc_trace(mVcdFile, exitcond4_fu_407_p2, "exitcond4_fu_407_p2");
    sc_trace(mVcdFile, tmp_49_fu_478_p2, "tmp_49_fu_478_p2");
    sc_trace(mVcdFile, tmp_49_reg_770, "tmp_49_reg_770");
    sc_trace(mVcdFile, i_5_fu_490_p2, "i_5_fu_490_p2");
    sc_trace(mVcdFile, i_5_reg_778, "i_5_reg_778");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_154, "ap_sig_bdd_154");
    sc_trace(mVcdFile, tmp_53_fu_525_p2, "tmp_53_fu_525_p2");
    sc_trace(mVcdFile, tmp_53_reg_783, "tmp_53_reg_783");
    sc_trace(mVcdFile, exitcond3_fu_484_p2, "exitcond3_fu_484_p2");
    sc_trace(mVcdFile, j_5_fu_537_p2, "j_5_fu_537_p2");
    sc_trace(mVcdFile, j_5_reg_791, "j_5_reg_791");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_168, "ap_sig_bdd_168");
    sc_trace(mVcdFile, feature_map_addr_1_reg_796, "feature_map_addr_1_reg_796");
    sc_trace(mVcdFile, exitcond2_fu_531_p2, "exitcond2_fu_531_p2");
    sc_trace(mVcdFile, lt_i_1_fu_567_p2, "lt_i_1_fu_567_p2");
    sc_trace(mVcdFile, lt_i_1_reg_804, "lt_i_1_reg_804");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_182, "ap_sig_bdd_182");
    sc_trace(mVcdFile, tmp_58_fu_604_p2, "tmp_58_fu_604_p2");
    sc_trace(mVcdFile, tmp_58_reg_809, "tmp_58_reg_809");
    sc_trace(mVcdFile, exitcond1_fu_561_p2, "exitcond1_fu_561_p2");
    sc_trace(mVcdFile, tmp_61_fu_639_p2, "tmp_61_fu_639_p2");
    sc_trace(mVcdFile, tmp_61_reg_814, "tmp_61_reg_814");
    sc_trace(mVcdFile, lt_j_1_fu_655_p2, "lt_j_1_fu_655_p2");
    sc_trace(mVcdFile, lt_j_1_reg_822, "lt_j_1_reg_822");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_198, "ap_sig_bdd_198");
    sc_trace(mVcdFile, exitcond_fu_649_p2, "exitcond_fu_649_p2");
    sc_trace(mVcdFile, grp_fu_222_p2, "grp_fu_222_p2");
    sc_trace(mVcdFile, tmp_28_reg_847, "tmp_28_reg_847");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_bdd_223, "ap_sig_bdd_223");
    sc_trace(mVcdFile, feature_map_load_reg_852, "feature_map_load_reg_852");
    sc_trace(mVcdFile, grp_fu_218_p2, "grp_fu_218_p2");
    sc_trace(mVcdFile, tmp_29_reg_857, "tmp_29_reg_857");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_bdd_233, "ap_sig_bdd_233");
    sc_trace(mVcdFile, filt_reg_117, "filt_reg_117");
    sc_trace(mVcdFile, i_reg_128, "i_reg_128");
    sc_trace(mVcdFile, j_reg_139, "j_reg_139");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_255, "ap_sig_bdd_255");
    sc_trace(mVcdFile, filt1_reg_150, "filt1_reg_150");
    sc_trace(mVcdFile, ch_reg_161, "ch_reg_161");
    sc_trace(mVcdFile, i2_reg_172, "i2_reg_172");
    sc_trace(mVcdFile, j3_reg_184, "j3_reg_184");
    sc_trace(mVcdFile, lt_i_reg_196, "lt_i_reg_196");
    sc_trace(mVcdFile, lt_j_reg_207, "lt_j_reg_207");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_bdd_288, "ap_sig_bdd_288");
    sc_trace(mVcdFile, tmp_fu_240_p1, "tmp_fu_240_p1");
    sc_trace(mVcdFile, tmp_63_cast_fu_343_p1, "tmp_63_cast_fu_343_p1");
    sc_trace(mVcdFile, tmp_68_cast_fu_552_p1, "tmp_68_cast_fu_552_p1");
    sc_trace(mVcdFile, tmp_76_cast_fu_670_p1, "tmp_76_cast_fu_670_p1");
    sc_trace(mVcdFile, tmp_77_cast_fu_690_p1, "tmp_77_cast_fu_690_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_301, "ap_sig_bdd_301");
    sc_trace(mVcdFile, tmp_s_fu_245_p3, "tmp_s_fu_245_p3");
    sc_trace(mVcdFile, tmp_37_fu_257_p3, "tmp_37_fu_257_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_265_p1, "p_shl1_cast_fu_265_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_253_p1, "p_shl_cast_fu_253_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_287_p1, "tmp_17_cast_fu_287_p1");
    sc_trace(mVcdFile, tmp_43_fu_291_p2, "tmp_43_fu_291_p2");
    sc_trace(mVcdFile, tmp_35_fu_304_p3, "tmp_35_fu_304_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_296_p3, "p_shl2_cast_fu_296_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_312_p1, "p_shl3_cast_fu_312_p1");
    sc_trace(mVcdFile, tmp_19_cast_fu_334_p1, "tmp_19_cast_fu_334_p1");
    sc_trace(mVcdFile, tmp_39_fu_363_p3, "tmp_39_fu_363_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_375_p1, "p_shl6_cast_fu_375_p1");
    sc_trace(mVcdFile, tmp_cast_fu_359_p1, "tmp_cast_fu_359_p1");
    sc_trace(mVcdFile, tmp_40_fu_379_p2, "tmp_40_fu_379_p2");
    sc_trace(mVcdFile, tmp_41_fu_389_p3, "tmp_41_fu_389_p3");
    sc_trace(mVcdFile, p_shl6_cast1_fu_371_p1, "p_shl6_cast1_fu_371_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_397_p1, "p_shl4_cast_fu_397_p1");
    sc_trace(mVcdFile, tmp_45_fu_423_p3, "tmp_45_fu_423_p3");
    sc_trace(mVcdFile, tmp_46_fu_435_p3, "tmp_46_fu_435_p3");
    sc_trace(mVcdFile, p_shl8_cast_fu_431_p1, "p_shl8_cast_fu_431_p1");
    sc_trace(mVcdFile, p_shl9_cast_fu_443_p1, "p_shl9_cast_fu_443_p1");
    sc_trace(mVcdFile, tmp_47_fu_447_p2, "tmp_47_fu_447_p2");
    sc_trace(mVcdFile, tmp_18_cast_fu_419_p1, "tmp_18_cast_fu_419_p1");
    sc_trace(mVcdFile, tmp_48_fu_457_p2, "tmp_48_fu_457_p2");
    sc_trace(mVcdFile, tmp_36_fu_466_p3, "tmp_36_fu_466_p3");
    sc_trace(mVcdFile, tmp_60_cast_fu_462_p1, "tmp_60_cast_fu_462_p1");
    sc_trace(mVcdFile, p_shl7_fu_474_p1, "p_shl7_fu_474_p1");
    sc_trace(mVcdFile, tmp_20_cast_fu_496_p1, "tmp_20_cast_fu_496_p1");
    sc_trace(mVcdFile, tmp_51_fu_500_p2, "tmp_51_fu_500_p2");
    sc_trace(mVcdFile, tmp_52_fu_513_p3, "tmp_52_fu_513_p3");
    sc_trace(mVcdFile, p_shl10_cast_fu_505_p3, "p_shl10_cast_fu_505_p3");
    sc_trace(mVcdFile, p_shl11_cast_fu_521_p1, "p_shl11_cast_fu_521_p1");
    sc_trace(mVcdFile, tmp_21_cast_fu_543_p1, "tmp_21_cast_fu_543_p1");
    sc_trace(mVcdFile, tmp_54_fu_547_p2, "tmp_54_fu_547_p2");
    sc_trace(mVcdFile, lt_i_cast4_fu_557_p1, "lt_i_cast4_fu_557_p1");
    sc_trace(mVcdFile, tmp_23_fu_579_p1, "tmp_23_fu_579_p1");
    sc_trace(mVcdFile, tmp_55_fu_583_p2, "tmp_55_fu_583_p2");
    sc_trace(mVcdFile, tmp_57_fu_592_p1, "tmp_57_fu_592_p1");
    sc_trace(mVcdFile, p_shl14_cast_fu_596_p3, "p_shl14_cast_fu_596_p3");
    sc_trace(mVcdFile, tmp_56_fu_588_p1, "tmp_56_fu_588_p1");
    sc_trace(mVcdFile, tmp_22_fu_573_p2, "tmp_22_fu_573_p2");
    sc_trace(mVcdFile, tmp_24_cast_fu_610_p1, "tmp_24_cast_fu_610_p1");
    sc_trace(mVcdFile, tmp_59_fu_614_p2, "tmp_59_fu_614_p2");
    sc_trace(mVcdFile, tmp_60_fu_619_p1, "tmp_60_fu_619_p1");
    sc_trace(mVcdFile, p_shl12_cast_fu_623_p3, "p_shl12_cast_fu_623_p3");
    sc_trace(mVcdFile, p_shl13_cast_fu_631_p3, "p_shl13_cast_fu_631_p3");
    sc_trace(mVcdFile, tmp_25_cast_fu_661_p1, "tmp_25_cast_fu_661_p1");
    sc_trace(mVcdFile, tmp_62_fu_665_p2, "tmp_62_fu_665_p2");
    sc_trace(mVcdFile, lt_j_cast2_fu_645_p1, "lt_j_cast2_fu_645_p1");
    sc_trace(mVcdFile, tmp_26_fu_675_p2, "tmp_26_fu_675_p2");
    sc_trace(mVcdFile, tmp_27_cast_fu_681_p1, "tmp_27_cast_fu_681_p1");
    sc_trace(mVcdFile, tmp_63_fu_685_p2, "tmp_63_fu_685_p2");
    sc_trace(mVcdFile, grp_fu_218_ce, "grp_fu_218_ce");
    sc_trace(mVcdFile, grp_fu_222_ce, "grp_fu_222_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Conv_Accel_conv_hw_24_3_10_5_20_s::~Conv_Accel_conv_hw_24_3_10_5_20_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete Conv_Accel_fadd_32ns_32ns_32_5_full_dsp_U0;
    delete Conv_Accel_fmul_32ns_32ns_32_4_max_dsp_U1;
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_484_p2.read()))) {
        ch_reg_161 = ch_3_reg_760.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_347_p2.read()))) {
        ch_reg_161 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_407_p2.read()))) {
        filt1_reg_150 = filt_5_reg_742.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond8_fu_228_p2.read(), ap_const_lv1_0))) {
        filt1_reg_150 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_275_p2.read()))) {
        filt_reg_117 = filt_4_reg_698.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        filt_reg_117 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_531_p2.read()))) {
        i2_reg_172 = i_5_reg_778.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_407_p2.read()))) {
        i2_reg_172 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_322_p2.read()))) {
        i_reg_128 = i_4_reg_716.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond8_fu_228_p2.read(), ap_const_lv1_0))) {
        i_reg_128 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_561_p2.read()))) {
        j3_reg_184 = j_5_reg_791.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_484_p2.read()))) {
        j3_reg_184 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_275_p2.read()))) {
        j_reg_139 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        j_reg_139 = j_4_reg_729.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_649_p2.read()))) {
        lt_i_reg_196 = lt_i_1_reg_804.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_531_p2.read()))) {
        lt_i_reg_196 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_561_p2.read()))) {
        lt_j_reg_207 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        lt_j_reg_207 = lt_j_1_reg_822.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond8_fu_228_p2.read(), ap_const_lv1_0))) {
        bias_addr_reg_708 =  (sc_lv<4>) (tmp_fu_240_p1.read());
        tmp_38_reg_703 = tmp_38_fu_269_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        ch_3_reg_760 = ch_3_fu_413_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_531_p2.read()))) {
        feature_map_addr_1_reg_796 =  (sc_lv<12>) (tmp_68_cast_fu_552_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        feature_map_load_reg_852 = feature_map_q0.read();
        tmp_28_reg_847 = grp_fu_222_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        filt_4_reg_698 = filt_4_fu_234_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        filt_5_reg_742 = filt_5_fu_353_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_4_reg_716 = i_4_fu_281_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        i_5_reg_778 = i_5_fu_490_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        j_4_reg_729 = j_4_fu_328_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        j_5_reg_791 = j_5_fu_537_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        lt_i_1_reg_804 = lt_i_1_fu_567_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        lt_j_1_reg_822 = lt_j_1_fu_655_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        tmp_29_reg_857 = grp_fu_218_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_347_p2.read()))) {
        tmp_42_reg_752 = tmp_42_fu_401_p2.read();
        tmp_49_cast_reg_747 = tmp_49_cast_fu_385_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_275_p2.read()))) {
        tmp_44_reg_721 = tmp_44_fu_316_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_407_p2.read()))) {
        tmp_49_reg_770 = tmp_49_fu_478_p2.read();
        tmp_59_cast_reg_765 = tmp_59_cast_fu_453_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_322_p2.read()))) {
        tmp_50_reg_734 = tmp_50_fu_338_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_484_p2.read()))) {
        tmp_53_reg_783 = tmp_53_fu_525_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_561_p2.read()))) {
        tmp_58_reg_809 = tmp_58_fu_604_p2.read();
        tmp_61_reg_814 = tmp_61_fu_639_p2.read();
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_347_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_347_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_108() {
    ap_sig_bdd_108 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_122() {
    ap_sig_bdd_122 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_138() {
    ap_sig_bdd_138 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_154() {
    ap_sig_bdd_154 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_168() {
    ap_sig_bdd_168 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_182() {
    ap_sig_bdd_182 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_198() {
    ap_sig_bdd_198 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_223() {
    ap_sig_bdd_223 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_233() {
    ap_sig_bdd_233 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_255() {
    ap_sig_bdd_255 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_288() {
    ap_sig_bdd_288 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_301() {
    ap_sig_bdd_301 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_39() {
    ap_sig_bdd_39 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_77() {
    ap_sig_bdd_77 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_bdd_94() {
    ap_sig_bdd_94 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_182.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_198.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_301.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_bdd_223.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_39.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_bdd_233.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_bdd_288.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_77.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_94.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_108.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_255.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_122.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_138.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_154.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_168.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_bias_address0() {
    bias_address0 = bias_addr_reg_708.read();
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_bias_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        bias_ce0 = ap_const_logic_1;
    } else {
        bias_ce0 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ch_3_fu_413_p2() {
    ch_3_fu_413_p2 = (!ch_reg_161.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(ch_reg_161.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond1_fu_561_p2() {
    exitcond1_fu_561_p2 = (!lt_i_reg_196.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(lt_i_reg_196.read() == ap_const_lv3_5);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond2_fu_531_p2() {
    exitcond2_fu_531_p2 = (!j3_reg_184.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(j3_reg_184.read() == ap_const_lv5_14);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond3_fu_484_p2() {
    exitcond3_fu_484_p2 = (!i2_reg_172.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i2_reg_172.read() == ap_const_lv5_14);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond4_fu_407_p2() {
    exitcond4_fu_407_p2 = (!ch_reg_161.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(ch_reg_161.read() == ap_const_lv2_3);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond5_fu_347_p2() {
    exitcond5_fu_347_p2 = (!filt1_reg_150.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(filt1_reg_150.read() == ap_const_lv4_A);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond6_fu_322_p2() {
    exitcond6_fu_322_p2 = (!j_reg_139.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_139.read() == ap_const_lv5_14);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond7_fu_275_p2() {
    exitcond7_fu_275_p2 = (!i_reg_128.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_128.read() == ap_const_lv5_14);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond8_fu_228_p2() {
    exitcond8_fu_228_p2 = (!filt_reg_117.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(filt_reg_117.read() == ap_const_lv4_A);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_exitcond_fu_649_p2() {
    exitcond_fu_649_p2 = (!lt_j_reg_207.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(lt_j_reg_207.read() == ap_const_lv3_5);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_feature_map_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        feature_map_address0 =  (sc_lv<12>) (tmp_63_cast_fu_343_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        feature_map_address0 = feature_map_addr_1_reg_796.read();
    } else {
        feature_map_address0 = "XXXXXXXXXXXX";
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_feature_map_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        feature_map_ce0 = ap_const_logic_1;
    } else {
        feature_map_ce0 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_feature_map_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        feature_map_d0 = tmp_29_reg_857.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        feature_map_d0 = bias_q0.read();
    } else {
        feature_map_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_feature_map_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()))) {
        feature_map_we0 = ap_const_logic_1;
    } else {
        feature_map_we0 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_filt_4_fu_234_p2() {
    filt_4_fu_234_p2 = (!filt_reg_117.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(filt_reg_117.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_filt_5_fu_353_p2() {
    filt_5_fu_353_p2 = (!filt1_reg_150.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(filt1_reg_150.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_filter_address0() {
    filter_address0 =  (sc_lv<10>) (tmp_76_cast_fu_670_p1.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_filter_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        filter_ce0 = ap_const_logic_1;
    } else {
        filter_ce0 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_grp_fu_218_ce() {
    grp_fu_218_ce = ap_const_logic_1;
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_grp_fu_222_ce() {
    grp_fu_222_ce = ap_const_logic_1;
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_i_4_fu_281_p2() {
    i_4_fu_281_p2 = (!i_reg_128.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_128.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_i_5_fu_490_p2() {
    i_5_fu_490_p2 = (!i2_reg_172.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i2_reg_172.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_image_r_address0() {
    image_r_address0 =  (sc_lv<11>) (tmp_77_cast_fu_690_p1.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_image_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        image_r_ce0 = ap_const_logic_1;
    } else {
        image_r_ce0 = ap_const_logic_0;
    }
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_j_4_fu_328_p2() {
    j_4_fu_328_p2 = (!j_reg_139.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j_reg_139.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_j_5_fu_537_p2() {
    j_5_fu_537_p2 = (!j3_reg_184.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j3_reg_184.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_lt_i_1_fu_567_p2() {
    lt_i_1_fu_567_p2 = (!lt_i_reg_196.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(lt_i_reg_196.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_lt_i_cast4_fu_557_p1() {
    lt_i_cast4_fu_557_p1 = esl_zext<5,3>(lt_i_reg_196.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_lt_j_1_fu_655_p2() {
    lt_j_1_fu_655_p2 = (!lt_j_reg_207.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(lt_j_reg_207.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_lt_j_cast2_fu_645_p1() {
    lt_j_cast2_fu_645_p1 = esl_zext<5,3>(lt_j_reg_207.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl10_cast_fu_505_p3() {
    p_shl10_cast_fu_505_p3 = esl_concat<9,4>(tmp_51_fu_500_p2.read(), ap_const_lv4_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl11_cast_fu_521_p1() {
    p_shl11_cast_fu_521_p1 = esl_zext<13,11>(tmp_52_fu_513_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl12_cast_fu_623_p3() {
    p_shl12_cast_fu_623_p3 = esl_concat<7,5>(tmp_60_fu_619_p1.read(), ap_const_lv5_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl13_cast_fu_631_p3() {
    p_shl13_cast_fu_631_p3 = esl_concat<9,3>(tmp_59_fu_614_p2.read(), ap_const_lv3_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl14_cast_fu_596_p3() {
    p_shl14_cast_fu_596_p3 = esl_concat<9,2>(tmp_57_fu_592_p1.read(), ap_const_lv2_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl1_cast_fu_265_p1() {
    p_shl1_cast_fu_265_p1 = esl_zext<9,6>(tmp_37_fu_257_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl2_cast_fu_296_p3() {
    p_shl2_cast_fu_296_p3 = esl_concat<9,4>(tmp_43_fu_291_p2.read(), ap_const_lv4_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl3_cast_fu_312_p1() {
    p_shl3_cast_fu_312_p1 = esl_zext<13,11>(tmp_35_fu_304_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl4_cast_fu_397_p1() {
    p_shl4_cast_fu_397_p1 = esl_zext<9,8>(tmp_41_fu_389_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl6_cast1_fu_371_p1() {
    p_shl6_cast1_fu_371_p1 = esl_zext<9,6>(tmp_39_fu_363_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl6_cast_fu_375_p1() {
    p_shl6_cast_fu_375_p1 = esl_zext<7,6>(tmp_39_fu_363_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl7_fu_474_p1() {
    p_shl7_fu_474_p1 = esl_sext<64,10>(tmp_36_fu_466_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl8_cast_fu_431_p1() {
    p_shl8_cast_fu_431_p1 = esl_zext<8,7>(tmp_45_fu_423_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl9_cast_fu_443_p1() {
    p_shl9_cast_fu_443_p1 = esl_zext<8,5>(tmp_46_fu_435_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_p_shl_cast_fu_253_p1() {
    p_shl_cast_fu_253_p1 = esl_zext<9,8>(tmp_s_fu_245_p3.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_17_cast_fu_287_p1() {
    tmp_17_cast_fu_287_p1 = esl_zext<9,5>(i_reg_128.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_18_cast_fu_419_p1() {
    tmp_18_cast_fu_419_p1 = esl_zext<8,2>(ch_reg_161.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_19_cast_fu_334_p1() {
    tmp_19_cast_fu_334_p1 = esl_zext<13,5>(j_reg_139.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_20_cast_fu_496_p1() {
    tmp_20_cast_fu_496_p1 = esl_zext<9,5>(i2_reg_172.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_21_cast_fu_543_p1() {
    tmp_21_cast_fu_543_p1 = esl_zext<13,5>(j3_reg_184.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_22_fu_573_p2() {
    tmp_22_fu_573_p2 = (!i2_reg_172.read().is_01() || !lt_i_cast4_fu_557_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(i2_reg_172.read()) + sc_biguint<5>(lt_i_cast4_fu_557_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_23_fu_579_p1() {
    tmp_23_fu_579_p1 = esl_zext<64,3>(lt_i_reg_196.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_24_cast_fu_610_p1() {
    tmp_24_cast_fu_610_p1 = esl_zext<9,5>(tmp_22_fu_573_p2.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_25_cast_fu_661_p1() {
    tmp_25_cast_fu_661_p1 = esl_zext<11,3>(lt_j_reg_207.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_26_fu_675_p2() {
    tmp_26_fu_675_p2 = (!lt_j_cast2_fu_645_p1.read().is_01() || !j3_reg_184.read().is_01())? sc_lv<5>(): (sc_biguint<5>(lt_j_cast2_fu_645_p1.read()) + sc_biguint<5>(j3_reg_184.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_27_cast_fu_681_p1() {
    tmp_27_cast_fu_681_p1 = esl_zext<12,5>(tmp_26_fu_675_p2.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_35_fu_304_p3() {
    tmp_35_fu_304_p3 = esl_concat<9,2>(tmp_43_fu_291_p2.read(), ap_const_lv2_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_36_fu_466_p3() {
    tmp_36_fu_466_p3 = esl_concat<8,2>(tmp_48_fu_457_p2.read(), ap_const_lv2_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_37_fu_257_p3() {
    tmp_37_fu_257_p3 = esl_concat<4,2>(filt_reg_117.read(), ap_const_lv2_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_38_fu_269_p2() {
    tmp_38_fu_269_p2 = (!p_shl1_cast_fu_265_p1.read().is_01() || !p_shl_cast_fu_253_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl1_cast_fu_265_p1.read()) + sc_biguint<9>(p_shl_cast_fu_253_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_39_fu_363_p3() {
    tmp_39_fu_363_p3 = esl_concat<4,2>(filt1_reg_150.read(), ap_const_lv2_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_40_fu_379_p2() {
    tmp_40_fu_379_p2 = (!p_shl6_cast_fu_375_p1.read().is_01() || !tmp_cast_fu_359_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(p_shl6_cast_fu_375_p1.read()) - sc_biguint<7>(tmp_cast_fu_359_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_41_fu_389_p3() {
    tmp_41_fu_389_p3 = esl_concat<4,4>(filt1_reg_150.read(), ap_const_lv4_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_42_fu_401_p2() {
    tmp_42_fu_401_p2 = (!p_shl6_cast1_fu_371_p1.read().is_01() || !p_shl4_cast_fu_397_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl6_cast1_fu_371_p1.read()) + sc_biguint<9>(p_shl4_cast_fu_397_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_43_fu_291_p2() {
    tmp_43_fu_291_p2 = (!tmp_17_cast_fu_287_p1.read().is_01() || !tmp_38_reg_703.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_17_cast_fu_287_p1.read()) + sc_biguint<9>(tmp_38_reg_703.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_44_fu_316_p2() {
    tmp_44_fu_316_p2 = (!p_shl2_cast_fu_296_p3.read().is_01() || !p_shl3_cast_fu_312_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl2_cast_fu_296_p3.read()) + sc_biguint<13>(p_shl3_cast_fu_312_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_45_fu_423_p3() {
    tmp_45_fu_423_p3 = esl_concat<2,5>(ch_reg_161.read(), ap_const_lv5_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_46_fu_435_p3() {
    tmp_46_fu_435_p3 = esl_concat<2,3>(ch_reg_161.read(), ap_const_lv3_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_47_fu_447_p2() {
    tmp_47_fu_447_p2 = (!p_shl8_cast_fu_431_p1.read().is_01() || !p_shl9_cast_fu_443_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl8_cast_fu_431_p1.read()) - sc_biguint<8>(p_shl9_cast_fu_443_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_48_fu_457_p2() {
    tmp_48_fu_457_p2 = (!tmp_49_cast_reg_747.read().is_01() || !tmp_18_cast_fu_419_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(tmp_49_cast_reg_747.read()) + sc_biguint<8>(tmp_18_cast_fu_419_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_49_cast_fu_385_p1() {
    tmp_49_cast_fu_385_p1 = esl_sext<8,7>(tmp_40_fu_379_p2.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_49_fu_478_p2() {
    tmp_49_fu_478_p2 = (!tmp_60_cast_fu_462_p1.read().is_01() || !p_shl7_fu_474_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(tmp_60_cast_fu_462_p1.read()) + sc_bigint<64>(p_shl7_fu_474_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_50_fu_338_p2() {
    tmp_50_fu_338_p2 = (!tmp_44_reg_721.read().is_01() || !tmp_19_cast_fu_334_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_44_reg_721.read()) + sc_biguint<13>(tmp_19_cast_fu_334_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_51_fu_500_p2() {
    tmp_51_fu_500_p2 = (!tmp_20_cast_fu_496_p1.read().is_01() || !tmp_42_reg_752.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_20_cast_fu_496_p1.read()) + sc_biguint<9>(tmp_42_reg_752.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_52_fu_513_p3() {
    tmp_52_fu_513_p3 = esl_concat<9,2>(tmp_51_fu_500_p2.read(), ap_const_lv2_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_53_fu_525_p2() {
    tmp_53_fu_525_p2 = (!p_shl10_cast_fu_505_p3.read().is_01() || !p_shl11_cast_fu_521_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl10_cast_fu_505_p3.read()) + sc_biguint<13>(p_shl11_cast_fu_521_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_54_fu_547_p2() {
    tmp_54_fu_547_p2 = (!tmp_53_reg_783.read().is_01() || !tmp_21_cast_fu_543_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_53_reg_783.read()) + sc_biguint<13>(tmp_21_cast_fu_543_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_55_fu_583_p2() {
    tmp_55_fu_583_p2 = (!tmp_23_fu_579_p1.read().is_01() || !tmp_49_reg_770.read().is_01())? sc_lv<64>(): (sc_biguint<64>(tmp_23_fu_579_p1.read()) + sc_biguint<64>(tmp_49_reg_770.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_56_fu_588_p1() {
    tmp_56_fu_588_p1 = tmp_55_fu_583_p2.read().range(11-1, 0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_57_fu_592_p1() {
    tmp_57_fu_592_p1 = tmp_55_fu_583_p2.read().range(9-1, 0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_58_fu_604_p2() {
    tmp_58_fu_604_p2 = (!p_shl14_cast_fu_596_p3.read().is_01() || !tmp_56_fu_588_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl14_cast_fu_596_p3.read()) + sc_biguint<11>(tmp_56_fu_588_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_59_cast_fu_453_p1() {
    tmp_59_cast_fu_453_p1 = esl_sext<9,8>(tmp_47_fu_447_p2.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_59_fu_614_p2() {
    tmp_59_fu_614_p2 = (!tmp_24_cast_fu_610_p1.read().is_01() || !tmp_59_cast_reg_765.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_24_cast_fu_610_p1.read()) + sc_bigint<9>(tmp_59_cast_reg_765.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_60_cast_fu_462_p1() {
    tmp_60_cast_fu_462_p1 = esl_sext<64,8>(tmp_48_fu_457_p2.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_60_fu_619_p1() {
    tmp_60_fu_619_p1 = tmp_59_fu_614_p2.read().range(7-1, 0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_61_fu_639_p2() {
    tmp_61_fu_639_p2 = (!p_shl12_cast_fu_623_p3.read().is_01() || !p_shl13_cast_fu_631_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl12_cast_fu_623_p3.read()) - sc_biguint<12>(p_shl13_cast_fu_631_p3.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_62_fu_665_p2() {
    tmp_62_fu_665_p2 = (!tmp_58_reg_809.read().is_01() || !tmp_25_cast_fu_661_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_58_reg_809.read()) + sc_biguint<11>(tmp_25_cast_fu_661_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_63_cast_fu_343_p1() {
    tmp_63_cast_fu_343_p1 = esl_zext<64,13>(tmp_50_reg_734.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_63_fu_685_p2() {
    tmp_63_fu_685_p2 = (!tmp_61_reg_814.read().is_01() || !tmp_27_cast_fu_681_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_61_reg_814.read()) + sc_biguint<12>(tmp_27_cast_fu_681_p1.read()));
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_68_cast_fu_552_p1() {
    tmp_68_cast_fu_552_p1 = esl_zext<64,13>(tmp_54_fu_547_p2.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_76_cast_fu_670_p1() {
    tmp_76_cast_fu_670_p1 = esl_zext<64,11>(tmp_62_fu_665_p2.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_77_cast_fu_690_p1() {
    tmp_77_cast_fu_690_p1 = esl_zext<64,12>(tmp_63_fu_685_p2.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_cast_fu_359_p1() {
    tmp_cast_fu_359_p1 = esl_zext<7,4>(filt1_reg_150.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_fu_240_p1() {
    tmp_fu_240_p1 = esl_zext<64,4>(filt_reg_117.read());
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_tmp_s_fu_245_p3() {
    tmp_s_fu_245_p3 = esl_concat<4,4>(filt_reg_117.read(), ap_const_lv4_0);
}

void Conv_Accel_conv_hw_24_3_10_5_20_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond8_fu_228_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_275_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_322_p2.read())) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_347_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 64 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_407_p2.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 128 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_484_p2.read())) {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 256 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_531_p2.read())) {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            } else {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            }
            break;
        case 512 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_561_p2.read())) {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 1024 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_649_p2.read())) {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

