// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xconv_accel.h"

extern XConv_accel_Config XConv_accel_ConfigTable[];

XConv_accel_Config *XConv_accel_LookupConfig(u16 DeviceId) {
	XConv_accel_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCONV_ACCEL_NUM_INSTANCES; Index++) {
		if (XConv_accel_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XConv_accel_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XConv_accel_Initialize(XConv_accel *InstancePtr, u16 DeviceId) {
	XConv_accel_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XConv_accel_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XConv_accel_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

