// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv_Accel_wrapped_conv_hw (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 8'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 8'b10;
parameter    ap_ST_pp1_stg0_fsm_2 = 8'b100;
parameter    ap_ST_st8_fsm_3 = 8'b1000;
parameter    ap_ST_st9_fsm_4 = 8'b10000;
parameter    ap_ST_st10_fsm_5 = 8'b100000;
parameter    ap_ST_pp3_stg0_fsm_6 = 8'b1000000;
parameter    ap_ST_st15_fsm_7 = 8'b10000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv11_6C0 = 11'b11011000000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv10_240 = 10'b1001000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv5_18 = 5'b11000;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv10_2EE = 10'b1011101110;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv7_4B = 7'b1001011;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv6_19 = 6'b11001;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_const_lv12_FA0 = 12'b111110100000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv10_190 = 10'b110010000;
parameter    ap_const_lv5_14 = 5'b10100;
parameter    ap_const_lv12_190 = 12'b110010000;
parameter    ap_const_lv12_F9F = 12'b111110011111;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] INPUT_STREAM_TDATA;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [3:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [4:0] INPUT_STREAM_TID;
input  [4:0] INPUT_STREAM_TDEST;
output  [31:0] OUTPUT_STREAM_TDATA;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [3:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [4:0] OUTPUT_STREAM_TID;
output  [4:0] OUTPUT_STREAM_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg INPUT_STREAM_TREADY;
reg OUTPUT_STREAM_TVALID;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm = 8'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_26;
reg   [10:0] indvar_flatten1_reg_268;
reg   [1:0] ch_reg_279;
reg   [9:0] indvar_flatten_reg_291;
reg   [4:0] i_reg_302;
reg   [4:0] j_reg_314;
reg   [9:0] indvar_flatten2_reg_326;
reg   [3:0] filt_reg_337;
reg   [6:0] indvar_flatten3_reg_348;
reg   [1:0] ch1_reg_359;
reg   [5:0] indvar_flatten4_reg_370;
reg   [2:0] i2_reg_381;
reg   [2:0] j3_reg_393;
reg   [11:0] indvar_flatten5_reg_416;
reg   [3:0] filt5_reg_427;
reg   [9:0] indvar_flatten6_reg_439;
reg   [4:0] i6_reg_450;
reg   [4:0] j7_reg_462;
reg   [31:0] reg_486;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_90;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
wire   [0:0] exitcond_flatten1_fu_490_p2;
reg    ap_sig_bdd_100;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg   [31:0] ap_reg_ppstg_reg_486_pp0_it1;
reg   [31:0] ap_reg_ppstg_reg_486_pp1_it1;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_2;
reg    ap_sig_bdd_118;
wire   [0:0] exitcond_flatten4_fu_679_p2;
reg    ap_sig_bdd_123;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
reg    ap_reg_ppiten_pp1_it2 = 1'b0;
reg   [0:0] exitcond_flatten1_reg_1230;
reg   [0:0] ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1;
wire   [10:0] indvar_flatten_next1_fu_496_p2;
wire   [0:0] exitcond_flatten_fu_502_p2;
reg   [0:0] exitcond_flatten_reg_1239;
wire   [9:0] indvar_flatten_next_fu_514_p3;
wire   [1:0] ch_mid2_fu_552_p3;
reg   [1:0] ch_mid2_reg_1252;
wire   [7:0] tmp_3_fu_583_p2;
reg   [7:0] tmp_3_reg_1257;
wire   [4:0] j_mid2_fu_600_p3;
reg   [4:0] j_mid2_reg_1262;
wire   [4:0] i_mid2_fu_608_p3;
reg   [4:0] i_mid2_reg_1267;
wire   [4:0] j_1_fu_616_p2;
reg   [4:0] j_1_reg_1273;
reg   [0:0] exitcond_flatten4_reg_1278;
reg   [0:0] ap_reg_ppstg_exitcond_flatten4_reg_1278_pp1_it1;
wire   [9:0] indvar_flatten_next4_fu_685_p2;
wire   [0:0] exitcond_flatten2_fu_697_p2;
reg   [0:0] exitcond_flatten2_reg_1287;
wire   [0:0] exitcond_flatten24_mid_fu_735_p2;
reg   [0:0] exitcond_flatten24_mid_reg_1292;
wire   [3:0] filt_mid2_fu_741_p3;
reg   [3:0] filt_mid2_reg_1297;
wire   [0:0] tmp_18_fu_781_p2;
reg   [0:0] tmp_18_reg_1302;
wire   [0:0] exitcond4_mid1_fu_799_p2;
reg   [0:0] exitcond4_mid1_reg_1307;
wire   [1:0] ch1_mid2_fu_805_p3;
reg   [1:0] ch1_mid2_reg_1313;
wire   [7:0] tmp_19_fu_817_p2;
reg   [7:0] tmp_19_reg_1318;
wire   [5:0] indvar_flatten_next2_fu_829_p3;
wire   [6:0] indvar_flatten_next3_fu_843_p3;
wire   [2:0] i2_mid2_fu_901_p3;
reg   [2:0] i2_mid2_reg_1334;
wire   [10:0] tmp_28_fu_944_p2;
reg   [10:0] tmp_28_reg_1339;
wire   [2:0] j_2_fu_950_p2;
wire   [3:0] filt_1_fu_971_p2;
reg    ap_sig_cseq_ST_st8_fsm_3;
reg    ap_sig_bdd_204;
wire   [0:0] exitcond3_fu_965_p2;
reg    ap_sig_bdd_209;
wire   [0:0] exitcond_flatten6_fu_987_p2;
reg   [0:0] exitcond_flatten6_reg_1357;
reg    ap_sig_cseq_ST_pp3_stg0_fsm_6;
reg    ap_sig_bdd_219;
reg    ap_reg_ppiten_pp3_it0 = 1'b0;
reg    ap_reg_ppiten_pp3_it1 = 1'b0;
reg    ap_reg_ppiten_pp3_it2 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2;
reg    ap_sig_ioackin_OUTPUT_STREAM_TREADY;
reg    ap_reg_ppiten_pp3_it3 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1;
wire   [11:0] indvar_flatten_next6_fu_993_p2;
wire   [0:0] exitcond_flatten5_fu_999_p2;
reg   [0:0] exitcond_flatten5_reg_1366;
wire   [9:0] indvar_flatten_next5_fu_1011_p3;
wire   [3:0] filt5_mid2_fu_1049_p3;
reg   [3:0] filt5_mid2_reg_1379;
wire   [11:0] tmp_7_fu_1060_p2;
reg   [11:0] tmp_7_reg_1384;
wire   [4:0] j7_mid2_fu_1107_p3;
reg   [4:0] j7_mid2_reg_1389;
wire   [4:0] i6_mid2_fu_1115_p3;
reg   [4:0] i6_mid2_reg_1395;
wire   [8:0] tmp_33_fu_1127_p2;
reg   [8:0] tmp_33_reg_1402;
wire   [4:0] j_3_fu_1133_p2;
reg   [4:0] j_3_reg_1408;
wire   [0:0] last_assign_fu_1219_p2;
reg   [0:0] last_assign_reg_1418;
reg    ap_sig_cseq_ST_st10_fsm_5;
reg    ap_sig_bdd_288;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done;
reg   [10:0] image_address0;
reg    image_ce0;
reg    image_we0;
wire   [31:0] image_d0;
wire   [31:0] image_q0;
reg   [9:0] filter_address0;
reg    filter_ce0;
reg    filter_we0;
wire   [31:0] filter_d0;
wire   [31:0] filter_q0;
reg   [3:0] bias_address0;
reg    bias_ce0;
reg    bias_we0;
wire   [31:0] bias_d0;
wire   [31:0] bias_q0;
reg   [11:0] feature_map_address0;
reg    feature_map_ce0;
reg    feature_map_we0;
wire   [31:0] feature_map_d0;
wire   [31:0] feature_map_q0;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_idle;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_ready;
wire   [10:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_address0;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_ce0;
wire   [31:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_q0;
wire   [9:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_address0;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_ce0;
wire   [31:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_q0;
wire   [3:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_address0;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_ce0;
wire   [31:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_q0;
wire   [11:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_address0;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_ce0;
wire    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_we0;
wire   [31:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_d0;
wire   [31:0] grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_q0;
reg   [1:0] ch_phi_fu_283_p4;
reg   [4:0] i_phi_fu_306_p4;
reg   [4:0] j_phi_fu_318_p4;
reg   [3:0] filt_phi_fu_341_p4;
reg   [1:0] ch1_phi_fu_363_p4;
reg   [2:0] i2_phi_fu_385_p4;
reg   [2:0] j3_phi_fu_397_p4;
reg   [3:0] filt4_reg_405;
reg   [3:0] filt5_phi_fu_431_p4;
reg   [4:0] i6_phi_fu_454_p4;
reg   [4:0] j7_phi_fu_466_p4;
reg    grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st9_fsm_4;
reg    ap_sig_bdd_405;
wire   [63:0] tmp_23_cast_fu_674_p1;
wire   [63:0] tmp_34_cast_fu_961_p1;
wire   [63:0] tmp_s_fu_982_p1;
wire   [63:0] tmp_44_cast_fu_1214_p1;
reg    ap_reg_ioackin_OUTPUT_STREAM_TREADY = 1'b0;
wire   [9:0] indvar_flatten_op_fu_508_p2;
wire   [0:0] exitcond_fu_540_p2;
wire   [0:0] not_exitcond_flatten_fu_535_p2;
wire   [1:0] ch_1_fu_522_p2;
wire   [6:0] tmp_1_fu_559_p3;
wire   [4:0] tmp_8_fu_571_p3;
wire   [7:0] p_shl1_cast_fu_567_p1;
wire   [7:0] p_shl2_cast_fu_579_p1;
wire   [4:0] i_mid_fu_528_p3;
wire   [0:0] exitcond8_mid_fu_546_p2;
wire   [0:0] tmp_5_fu_595_p2;
wire   [4:0] i_1_fu_589_p2;
wire   [8:0] tmp_6_cast_fu_625_p1;
wire  signed [8:0] tmp_17_cast_fu_622_p1;
wire   [8:0] tmp_6_fu_628_p2;
wire   [6:0] tmp_9_fu_634_p1;
wire   [11:0] p_shl_cast_fu_638_p3;
wire   [11:0] p_shl3_cast_fu_646_p3;
wire   [11:0] tmp_5_cast_fu_665_p1;
wire   [11:0] tmp_11_fu_654_p2;
wire   [11:0] tmp_13_fu_668_p2;
wire   [0:0] exitcond1_fu_717_p2;
wire   [0:0] not_exitcond_flatten1_fu_711_p2;
wire   [0:0] exitcond_flatten3_fu_729_p2;
wire   [3:0] filt_2_fu_691_p2;
wire   [5:0] tmp_16_fu_753_p3;
wire   [6:0] p_shl4_cast_fu_761_p1;
wire   [6:0] tmp_3_cast_fu_749_p1;
wire   [6:0] tmp_17_fu_765_p2;
wire   [1:0] ch1_mid_fu_703_p3;
wire   [0:0] exitcond_flatten24_not_fu_787_p2;
wire   [0:0] exitcond4_mid_fu_723_p2;
wire   [0:0] not_exitcond_flatten24_mid_fu_793_p2;
wire   [1:0] ch_2_fu_775_p2;
wire   [7:0] tmp_9_cast_fu_813_p1;
wire  signed [7:0] tmp_25_cast_fu_771_p1;
wire   [5:0] indvar_flatten22_op_fu_823_p2;
wire   [6:0] indvar_flatten36_op_fu_837_p2;
wire   [9:0] tmp_20_fu_861_p3;
wire  signed [63:0] p_shl7_fu_868_p1;
wire  signed [63:0] tmp_27_cast_fu_858_p1;
wire   [2:0] i2_mid_fu_851_p3;
wire   [0:0] tmp_22_fu_884_p2;
wire   [0:0] tmp_23_fu_888_p2;
wire   [2:0] i_2_fu_878_p2;
wire   [63:0] tmp_10_fu_908_p1;
wire   [63:0] tmp_21_fu_872_p2;
wire   [63:0] tmp_24_fu_912_p2;
wire   [8:0] tmp_26_fu_922_p1;
wire   [10:0] p_shl8_cast_fu_926_p3;
wire   [10:0] tmp_25_fu_918_p1;
wire   [2:0] j3_mid2_fu_893_p3;
wire   [10:0] tmp_13_cast_fu_940_p1;
wire   [10:0] tmp_27_fu_934_p2;
wire   [9:0] indvar_flatten66_op_fu_1005_p2;
wire   [0:0] exitcond2_fu_1037_p2;
wire   [0:0] not_exitcond_flatten2_fu_1032_p2;
wire   [3:0] filt_3_fu_1019_p2;
wire   [3:0] tmp_7_fu_1060_p0;
wire   [7:0] tmp_29_fu_1066_p3;
wire   [5:0] tmp_30_fu_1078_p3;
wire   [8:0] p_shl9_cast_fu_1074_p1;
wire   [8:0] p_shl10_cast_fu_1086_p1;
wire   [4:0] i6_mid_fu_1025_p3;
wire   [0:0] exitcond_mid_fu_1043_p2;
wire   [0:0] tmp_32_fu_1102_p2;
wire   [4:0] i_3_fu_1096_p2;
wire   [8:0] tmp_11_cast_fu_1123_p1;
wire   [8:0] tmp_31_fu_1090_p2;
wire   [6:0] p_shl6_fu_1146_p3;
wire   [10:0] tmp_34_fu_1164_p3;
wire   [12:0] p_shl11_cast_fu_1157_p3;
wire   [12:0] p_shl12_cast_fu_1171_p1;
wire   [8:0] p_shl5_fu_1139_p3;
wire   [8:0] p_shl6_cast_fu_1153_p1;
wire   [8:0] tmp_fu_1181_p2;
wire   [11:0] j7_cast3_fu_1191_p1;
wire   [11:0] tmp1_fu_1194_p2;
wire   [11:0] tmp_cast_fu_1187_p1;
wire   [12:0] tmp_16_cast_fu_1205_p1;
wire   [12:0] tmp_35_fu_1175_p2;
wire   [12:0] tmp_36_fu_1208_p2;
wire   [11:0] tmp_15_fu_1199_p2;
reg    ap_sig_cseq_ST_st15_fsm_7;
reg    ap_sig_bdd_931;
reg   [7:0] ap_NS_fsm;
wire   [11:0] tmp_7_fu_1060_p00;


Conv_Accel_wrapped_conv_hw_image #(
    .DataWidth( 32 ),
    .AddressRange( 1728 ),
    .AddressWidth( 11 ))
image_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( image_address0 ),
    .ce0( image_ce0 ),
    .we0( image_we0 ),
    .d0( image_d0 ),
    .q0( image_q0 )
);

Conv_Accel_wrapped_conv_hw_filter #(
    .DataWidth( 32 ),
    .AddressRange( 750 ),
    .AddressWidth( 10 ))
filter_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( filter_address0 ),
    .ce0( filter_ce0 ),
    .we0( filter_we0 ),
    .d0( filter_d0 ),
    .q0( filter_q0 )
);

Conv_Accel_wrapped_conv_hw_bias #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
bias_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( bias_address0 ),
    .ce0( bias_ce0 ),
    .we0( bias_we0 ),
    .d0( bias_d0 ),
    .q0( bias_q0 )
);

Conv_Accel_wrapped_conv_hw_feature_map #(
    .DataWidth( 32 ),
    .AddressRange( 4000 ),
    .AddressWidth( 12 ))
feature_map_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( feature_map_address0 ),
    .ce0( feature_map_ce0 ),
    .we0( feature_map_we0 ),
    .d0( feature_map_d0 ),
    .q0( feature_map_q0 )
);

Conv_Accel_conv_hw_24_3_10_5_20_s grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start ),
    .ap_done( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done ),
    .ap_idle( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_idle ),
    .ap_ready( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_ready ),
    .image_r_address0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_address0 ),
    .image_r_ce0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_ce0 ),
    .image_r_q0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_q0 ),
    .filter_address0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_address0 ),
    .filter_ce0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_ce0 ),
    .filter_q0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_q0 ),
    .bias_address0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_address0 ),
    .bias_ce0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_ce0 ),
    .bias_q0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_q0 ),
    .feature_map_address0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_address0 ),
    .feature_map_ce0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_ce0 ),
    .feature_map_we0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_we0 ),
    .feature_map_d0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_d0 ),
    .feature_map_q0( grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_q0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_OUTPUT_STREAM_TREADY assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ioackin_OUTPUT_STREAM_TREADY
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_OUTPUT_STREAM_TREADY <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)))) begin
            ap_reg_ioackin_OUTPUT_STREAM_TREADY <= ap_const_logic_0;
        end else if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3) & (ap_const_logic_1 == OUTPUT_STREAM_TREADY))) begin
            ap_reg_ioackin_OUTPUT_STREAM_TREADY <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten1_fu_490_p2 == ap_const_lv1_0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & ~(ap_const_lv1_0 == exitcond_flatten4_fu_679_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it1 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & ~(ap_const_lv1_0 == exitcond_flatten4_fu_679_p2)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it2 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
    end else begin
        if (~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0))) begin
            ap_reg_ppiten_pp1_it2 <= ap_reg_ppiten_pp1_it1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp3_it0 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp3_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp3_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & ~(ap_const_lv1_0 == exitcond_flatten6_fu_987_p2))) begin
            ap_reg_ppiten_pp3_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5) & ~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done))) begin
            ap_reg_ppiten_pp3_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp3_it1 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp3_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp3_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == exitcond_flatten6_fu_987_p2))) begin
            ap_reg_ppiten_pp3_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5) & ~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & ~(ap_const_lv1_0 == exitcond_flatten6_fu_987_p2)))) begin
            ap_reg_ppiten_pp3_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp3_it2 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp3_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp3_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3))) begin
            ap_reg_ppiten_pp3_it2 <= ap_reg_ppiten_pp3_it1;
        end
    end
end

/// ap_reg_ppiten_pp3_it3 assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp3_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp3_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3))) begin
            ap_reg_ppiten_pp3_it3 <= ap_reg_ppiten_pp3_it2;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5) & ~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done))) begin
            ap_reg_ppiten_pp3_it3 <= ap_const_logic_0;
        end
    end
end

/// grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk) begin : ap_ret_grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_4)) begin
            grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_ready)) begin
            grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
        ch1_reg_359 <= ap_const_lv2_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & (ap_const_lv1_0 == exitcond_flatten4_reg_1278))) begin
        ch1_reg_359 <= ch1_mid2_reg_1313;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1))) begin
        ch_reg_279 <= ch_mid2_reg_1252;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        ch_reg_279 <= ap_const_lv2_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & ~(ap_const_lv1_0 == exitcond_flatten4_fu_679_p2))) begin
        filt4_reg_405 <= ap_const_lv4_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_3) & (ap_const_lv1_0 == exitcond3_fu_965_p2) & ~ap_sig_bdd_209)) begin
        filt4_reg_405 <= filt_1_fu_971_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1))) begin
        filt5_reg_427 <= filt5_mid2_reg_1379;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5) & ~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done))) begin
        filt5_reg_427 <= ap_const_lv4_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
        filt_reg_337 <= ap_const_lv4_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & (ap_const_lv1_0 == exitcond_flatten4_reg_1278))) begin
        filt_reg_337 <= filt_mid2_reg_1297;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
        i2_reg_381 <= ap_const_lv3_0;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten4_reg_1278_pp1_it1))) begin
        i2_reg_381 <= i2_mid2_reg_1334;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1))) begin
        i6_reg_450 <= i6_mid2_reg_1395;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5) & ~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done))) begin
        i6_reg_450 <= ap_const_lv5_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1))) begin
        i_reg_302 <= i_mid2_reg_1267;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        i_reg_302 <= ap_const_lv5_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten1_fu_490_p2 == ap_const_lv1_0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100))) begin
        indvar_flatten1_reg_268 <= indvar_flatten_next1_fu_496_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        indvar_flatten1_reg_268 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
        indvar_flatten2_reg_326 <= ap_const_lv10_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)))) begin
        indvar_flatten2_reg_326 <= indvar_flatten_next4_fu_685_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
        indvar_flatten3_reg_348 <= ap_const_lv7_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)))) begin
        indvar_flatten3_reg_348 <= indvar_flatten_next3_fu_843_p3;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
        indvar_flatten4_reg_370 <= ap_const_lv6_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)))) begin
        indvar_flatten4_reg_370 <= indvar_flatten_next2_fu_829_p3;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == exitcond_flatten6_fu_987_p2))) begin
        indvar_flatten5_reg_416 <= indvar_flatten_next6_fu_993_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5) & ~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done))) begin
        indvar_flatten5_reg_416 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == exitcond_flatten6_fu_987_p2))) begin
        indvar_flatten6_reg_439 <= indvar_flatten_next5_fu_1011_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5) & ~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done))) begin
        indvar_flatten6_reg_439 <= ap_const_lv10_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten1_fu_490_p2 == ap_const_lv1_0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100))) begin
        indvar_flatten_reg_291 <= indvar_flatten_next_fu_514_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        indvar_flatten_reg_291 <= ap_const_lv10_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0))) begin
        j3_reg_393 <= ap_const_lv3_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & (ap_const_lv1_0 == exitcond_flatten4_reg_1278))) begin
        j3_reg_393 <= j_2_fu_950_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1))) begin
        j7_reg_462 <= j_3_reg_1408;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5) & ~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done))) begin
        j7_reg_462 <= ap_const_lv5_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1))) begin
        j_reg_314 <= j_1_reg_1273;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        j_reg_314 <= ap_const_lv5_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100))) begin
        ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1 <= exitcond_flatten1_reg_1230;
        ap_reg_ppstg_reg_486_pp0_it1 <= reg_486;
        exitcond_flatten1_reg_1230 <= exitcond_flatten1_fu_490_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)))) begin
        ap_reg_ppstg_exitcond_flatten4_reg_1278_pp1_it1 <= exitcond_flatten4_reg_1278;
        ap_reg_ppstg_reg_486_pp1_it1 <= reg_486;
        exitcond_flatten4_reg_1278 <= exitcond_flatten4_fu_679_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)))) begin
        ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1 <= exitcond_flatten6_reg_1357;
        exitcond_flatten6_reg_1357 <= exitcond_flatten6_fu_987_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3))) begin
        ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2 <= ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)))) begin
        ch1_mid2_reg_1313 <= ch1_mid2_fu_805_p3;
        filt_mid2_reg_1297 <= filt_mid2_fu_741_p3;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & (ap_const_lv1_0 == exitcond_flatten1_reg_1230))) begin
        ch_mid2_reg_1252 <= ch_mid2_fu_552_p3;
        i_mid2_reg_1267 <= i_mid2_fu_608_p3;
        j_1_reg_1273 <= j_1_fu_616_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)))) begin
        exitcond4_mid1_reg_1307 <= exitcond4_mid1_fu_799_p2;
        exitcond_flatten24_mid_reg_1292 <= exitcond_flatten24_mid_fu_735_p2;
        exitcond_flatten2_reg_1287 <= exitcond_flatten2_fu_697_p2;
        tmp_18_reg_1302 <= tmp_18_fu_781_p2;
        tmp_19_reg_1318 <= tmp_19_fu_817_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == exitcond_flatten6_fu_987_p2))) begin
        exitcond_flatten5_reg_1366 <= exitcond_flatten5_fu_999_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten1_fu_490_p2 == ap_const_lv1_0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100))) begin
        exitcond_flatten_reg_1239 <= exitcond_flatten_fu_502_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it1) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == exitcond_flatten6_reg_1357))) begin
        filt5_mid2_reg_1379 <= filt5_mid2_fu_1049_p3;
        i6_mid2_reg_1395 <= i6_mid2_fu_1115_p3;
        j_3_reg_1408 <= j_3_fu_1133_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & (ap_const_lv1_0 == exitcond_flatten4_reg_1278))) begin
        i2_mid2_reg_1334 <= i2_mid2_fu_901_p3;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_6) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == exitcond_flatten6_reg_1357))) begin
        j7_mid2_reg_1389 <= j7_mid2_fu_1107_p3;
        tmp_33_reg_1402 <= tmp_33_fu_1127_p2;
        tmp_7_reg_1384[11 : 4] <= tmp_7_fu_1060_p2[11 : 4];
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & (ap_const_lv1_0 == exitcond_flatten1_reg_1230))) begin
        j_mid2_reg_1262 <= j_mid2_fu_600_p3;
        tmp_3_reg_1257[7 : 3] <= tmp_3_fu_583_p2[7 : 3];
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if ((~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1))) begin
        last_assign_reg_1418 <= last_assign_fu_1219_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten1_fu_490_p2 == ap_const_lv1_0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0))))) begin
        reg_486 <= INPUT_STREAM_TDATA;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & (ap_const_lv1_0 == exitcond_flatten4_reg_1278))) begin
        tmp_28_reg_1339 <= tmp_28_fu_944_p2;
    end
end

/// INPUT_STREAM_TREADY assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or exitcond_flatten1_fu_490_p2 or ap_sig_bdd_100 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or exitcond_flatten4_fu_679_p2 or ap_sig_bdd_123 or ap_reg_ppiten_pp1_it0 or ap_sig_cseq_ST_st8_fsm_3 or exitcond3_fu_965_p2 or ap_sig_bdd_209) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten1_fu_490_p2 == ap_const_lv1_0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_3) & (ap_const_lv1_0 == exitcond3_fu_965_p2) & ~ap_sig_bdd_209))) begin
        INPUT_STREAM_TREADY = ap_const_logic_1;
    end else begin
        INPUT_STREAM_TREADY = ap_const_logic_0;
    end
end

/// OUTPUT_STREAM_TVALID assign process. ///
always @ (ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2 or ap_reg_ppiten_pp3_it3 or ap_reg_ioackin_OUTPUT_STREAM_TREADY) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3) & (ap_const_logic_0 == ap_reg_ioackin_OUTPUT_STREAM_TREADY))) begin
        OUTPUT_STREAM_TVALID = ap_const_logic_1;
    end else begin
        OUTPUT_STREAM_TVALID = ap_const_logic_0;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st15_fsm_7) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_7))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st15_fsm_7) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_7)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_1 assign process. ///
always @ (ap_sig_bdd_90) begin
    if (ap_sig_bdd_90) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp1_stg0_fsm_2 assign process. ///
always @ (ap_sig_bdd_118) begin
    if (ap_sig_bdd_118) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp3_stg0_fsm_6 assign process. ///
always @ (ap_sig_bdd_219) begin
    if (ap_sig_bdd_219) begin
        ap_sig_cseq_ST_pp3_stg0_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp3_stg0_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st10_fsm_5 assign process. ///
always @ (ap_sig_bdd_288) begin
    if (ap_sig_bdd_288) begin
        ap_sig_cseq_ST_st10_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st15_fsm_7 assign process. ///
always @ (ap_sig_bdd_931) begin
    if (ap_sig_bdd_931) begin
        ap_sig_cseq_ST_st15_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_26) begin
    if (ap_sig_bdd_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st8_fsm_3 assign process. ///
always @ (ap_sig_bdd_204) begin
    if (ap_sig_bdd_204) begin
        ap_sig_cseq_ST_st8_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st9_fsm_4 assign process. ///
always @ (ap_sig_bdd_405) begin
    if (ap_sig_bdd_405) begin
        ap_sig_cseq_ST_st9_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_OUTPUT_STREAM_TREADY assign process. ///
always @ (OUTPUT_STREAM_TREADY or ap_reg_ioackin_OUTPUT_STREAM_TREADY) begin
    if ((ap_const_logic_0 == ap_reg_ioackin_OUTPUT_STREAM_TREADY)) begin
        ap_sig_ioackin_OUTPUT_STREAM_TREADY = OUTPUT_STREAM_TREADY;
    end else begin
        ap_sig_ioackin_OUTPUT_STREAM_TREADY = ap_const_logic_1;
    end
end

/// bias_address0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_3 or ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_address0 or tmp_s_fu_982_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_3)) begin
        bias_address0 = tmp_s_fu_982_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        bias_address0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_address0;
    end else begin
        bias_address0 = 'bx;
    end
end

/// bias_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_3 or ap_sig_bdd_209 or ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_ce0) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_3) & ~ap_sig_bdd_209)) begin
        bias_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        bias_ce0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_ce0;
    end else begin
        bias_ce0 = ap_const_logic_0;
    end
end

/// bias_we0 assign process. ///
always @ (ap_sig_cseq_ST_st8_fsm_3 or exitcond3_fu_965_p2 or ap_sig_bdd_209) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_3) & (ap_const_lv1_0 == exitcond3_fu_965_p2) & ~ap_sig_bdd_209)) begin
        bias_we0 = ap_const_logic_1;
    end else begin
        bias_we0 = ap_const_logic_0;
    end
end

/// ch1_phi_fu_363_p4 assign process. ///
always @ (ch1_reg_359 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or exitcond_flatten4_reg_1278 or ch1_mid2_reg_1313) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten4_reg_1278))) begin
        ch1_phi_fu_363_p4 = ch1_mid2_reg_1313;
    end else begin
        ch1_phi_fu_363_p4 = ch1_reg_359;
    end
end

/// ch_phi_fu_283_p4 assign process. ///
always @ (ch_reg_279 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1 or ch_mid2_reg_1252) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1))) begin
        ch_phi_fu_283_p4 = ch_mid2_reg_1252;
    end else begin
        ch_phi_fu_283_p4 = ch_reg_279;
    end
end

/// feature_map_address0 assign process. ///
always @ (ap_reg_ppiten_pp3_it2 or ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_address0 or tmp_44_cast_fu_1214_p1) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp3_it2)) begin
        feature_map_address0 = tmp_44_cast_fu_1214_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        feature_map_address0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_address0;
    end else begin
        feature_map_address0 = 'bx;
    end
end

/// feature_map_ce0 assign process. ///
always @ (ap_reg_ppiten_pp3_it2 or ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2 or ap_sig_ioackin_OUTPUT_STREAM_TREADY or ap_reg_ppiten_pp3_it3 or ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_ce0) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)))) begin
        feature_map_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        feature_map_ce0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_ce0;
    end else begin
        feature_map_ce0 = ap_const_logic_0;
    end
end

/// feature_map_we0 assign process. ///
always @ (ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_we0) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        feature_map_we0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_we0;
    end else begin
        feature_map_we0 = ap_const_logic_0;
    end
end

/// filt5_phi_fu_431_p4 assign process. ///
always @ (filt5_reg_427 or ap_reg_ppiten_pp3_it2 or ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1 or filt5_mid2_reg_1379) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1))) begin
        filt5_phi_fu_431_p4 = filt5_mid2_reg_1379;
    end else begin
        filt5_phi_fu_431_p4 = filt5_reg_427;
    end
end

/// filt_phi_fu_341_p4 assign process. ///
always @ (filt_reg_337 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or exitcond_flatten4_reg_1278 or filt_mid2_reg_1297) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten4_reg_1278))) begin
        filt_phi_fu_341_p4 = filt_mid2_reg_1297;
    end else begin
        filt_phi_fu_341_p4 = filt_reg_337;
    end
end

/// filter_address0 assign process. ///
always @ (ap_reg_ppiten_pp1_it2 or ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_address0 or tmp_34_cast_fu_961_p1) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) begin
        filter_address0 = tmp_34_cast_fu_961_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        filter_address0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_address0;
    end else begin
        filter_address0 = 'bx;
    end
end

/// filter_ce0 assign process. ///
always @ (ap_sig_bdd_123 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it2 or ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_ce0) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)))) begin
        filter_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        filter_ce0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_ce0;
    end else begin
        filter_ce0 = ap_const_logic_0;
    end
end

/// filter_we0 assign process. ///
always @ (ap_sig_bdd_123 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_flatten4_reg_1278_pp1_it1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten4_reg_1278_pp1_it1))) begin
        filter_we0 = ap_const_logic_1;
    end else begin
        filter_we0 = ap_const_logic_0;
    end
end

/// i2_phi_fu_385_p4 assign process. ///
always @ (i2_reg_381 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_flatten4_reg_1278_pp1_it1 or i2_mid2_reg_1334) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten4_reg_1278_pp1_it1))) begin
        i2_phi_fu_385_p4 = i2_mid2_reg_1334;
    end else begin
        i2_phi_fu_385_p4 = i2_reg_381;
    end
end

/// i6_phi_fu_454_p4 assign process. ///
always @ (i6_reg_450 or ap_reg_ppiten_pp3_it2 or ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1 or i6_mid2_reg_1395) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1))) begin
        i6_phi_fu_454_p4 = i6_mid2_reg_1395;
    end else begin
        i6_phi_fu_454_p4 = i6_reg_450;
    end
end

/// i_phi_fu_306_p4 assign process. ///
always @ (i_reg_302 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1 or i_mid2_reg_1267) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1))) begin
        i_phi_fu_306_p4 = i_mid2_reg_1267;
    end else begin
        i_phi_fu_306_p4 = i_reg_302;
    end
end

/// image_address0 assign process. ///
always @ (ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_address0 or tmp_23_cast_fu_674_p1) begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
        image_address0 = tmp_23_cast_fu_674_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        image_address0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_address0;
    end else begin
        image_address0 = 'bx;
    end
end

/// image_ce0 assign process. ///
always @ (ap_reg_ppiten_pp0_it0 or ap_sig_bdd_100 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_st10_fsm_5 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_ce0) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100))) begin
        image_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_5)) begin
        image_ce0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_ce0;
    end else begin
        image_ce0 = ap_const_logic_0;
    end
end

/// image_we0 assign process. ///
always @ (ap_reg_ppiten_pp0_it0 or ap_sig_bdd_100 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1))) begin
        image_we0 = ap_const_logic_1;
    end else begin
        image_we0 = ap_const_logic_0;
    end
end

/// j3_phi_fu_397_p4 assign process. ///
always @ (j3_reg_393 or ap_sig_cseq_ST_pp1_stg0_fsm_2 or ap_reg_ppiten_pp1_it1 or exitcond_flatten4_reg_1278 or j_2_fu_950_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond_flatten4_reg_1278))) begin
        j3_phi_fu_397_p4 = j_2_fu_950_p2;
    end else begin
        j3_phi_fu_397_p4 = j3_reg_393;
    end
end

/// j7_phi_fu_466_p4 assign process. ///
always @ (j7_reg_462 or ap_reg_ppiten_pp3_it2 or ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1 or j_3_reg_1408) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it1))) begin
        j7_phi_fu_466_p4 = j_3_reg_1408;
    end else begin
        j7_phi_fu_466_p4 = j7_reg_462;
    end
end

/// j_phi_fu_318_p4 assign process. ///
always @ (j_reg_314 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1 or j_1_reg_1273) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten1_reg_1230_pp0_it1))) begin
        j_phi_fu_318_p4 = j_1_reg_1273;
    end else begin
        j_phi_fu_318_p4 = j_reg_314;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or exitcond_flatten1_fu_490_p2 or ap_sig_bdd_100 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or exitcond_flatten4_fu_679_p2 or ap_sig_bdd_123 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or exitcond3_fu_965_p2 or ap_sig_bdd_209 or exitcond_flatten6_fu_987_p2 or ap_reg_ppiten_pp3_it0 or ap_reg_ppiten_pp3_it1 or ap_reg_ppiten_pp3_it2 or ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2 or ap_sig_ioackin_OUTPUT_STREAM_TREADY or ap_reg_ppiten_pp3_it3 or grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_100) & ~(exitcond_flatten1_fu_490_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_pp1_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & ~(ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_123 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) & ~(ap_const_lv1_0 == exitcond_flatten4_fu_679_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
                ap_NS_fsm = ap_ST_st8_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_2;
            end
        end
        ap_ST_st8_fsm_3 : 
        begin
            if (((ap_const_lv1_0 == exitcond3_fu_965_p2) & ~ap_sig_bdd_209)) begin
                ap_NS_fsm = ap_ST_st8_fsm_3;
            end else if ((~ap_sig_bdd_209 & ~(ap_const_lv1_0 == exitcond3_fu_965_p2))) begin
                ap_NS_fsm = ap_ST_st9_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_3;
            end
        end
        ap_ST_st9_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st10_fsm_5;
        end
        ap_ST_st10_fsm_5 : 
        begin
            if (~(ap_const_logic_0 == grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_done)) begin
                ap_NS_fsm = ap_ST_pp3_stg0_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_5;
            end
        end
        ap_ST_pp3_stg0_fsm_6 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp3_it3) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp3_it2)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & ~(ap_const_lv1_0 == exitcond_flatten6_fu_987_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp3_it1)))) begin
                ap_NS_fsm = ap_ST_pp3_stg0_fsm_6;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp3_it3) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp3_it2)) | ((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ~((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten6_reg_1357_pp3_it2) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it3)) & ~(ap_const_lv1_0 == exitcond_flatten6_fu_987_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp3_it1)))) begin
                ap_NS_fsm = ap_ST_st15_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_pp3_stg0_fsm_6;
            end
        end
        ap_ST_st15_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OUTPUT_STREAM_TDATA = feature_map_q0;
assign OUTPUT_STREAM_TDEST = ap_const_lv5_0;
assign OUTPUT_STREAM_TID = ap_const_lv5_0;
assign OUTPUT_STREAM_TKEEP = ap_const_lv4_F;
assign OUTPUT_STREAM_TLAST = last_assign_reg_1418;
assign OUTPUT_STREAM_TSTRB = ap_const_lv4_F;
assign OUTPUT_STREAM_TUSER = ap_const_lv4_0;

/// ap_sig_bdd_100 assign process. ///
always @ (INPUT_STREAM_TVALID or exitcond_flatten1_fu_490_p2) begin
    ap_sig_bdd_100 = ((INPUT_STREAM_TVALID == ap_const_logic_0) & (exitcond_flatten1_fu_490_p2 == ap_const_lv1_0));
end

/// ap_sig_bdd_118 assign process. ///
always @ (ap_CS_fsm) begin
    ap_sig_bdd_118 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_123 assign process. ///
always @ (INPUT_STREAM_TVALID or exitcond_flatten4_fu_679_p2) begin
    ap_sig_bdd_123 = ((INPUT_STREAM_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_flatten4_fu_679_p2));
end

/// ap_sig_bdd_204 assign process. ///
always @ (ap_CS_fsm) begin
    ap_sig_bdd_204 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_209 assign process. ///
always @ (INPUT_STREAM_TVALID or exitcond3_fu_965_p2) begin
    ap_sig_bdd_209 = ((INPUT_STREAM_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == exitcond3_fu_965_p2));
end

/// ap_sig_bdd_219 assign process. ///
always @ (ap_CS_fsm) begin
    ap_sig_bdd_219 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_26 assign process. ///
always @ (ap_CS_fsm) begin
    ap_sig_bdd_26 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_288 assign process. ///
always @ (ap_CS_fsm) begin
    ap_sig_bdd_288 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_405 assign process. ///
always @ (ap_CS_fsm) begin
    ap_sig_bdd_405 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_90 assign process. ///
always @ (ap_CS_fsm) begin
    ap_sig_bdd_90 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_931 assign process. ///
always @ (ap_CS_fsm) begin
    ap_sig_bdd_931 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end
assign bias_d0 = INPUT_STREAM_TDATA;
assign ch1_mid2_fu_805_p3 = ((exitcond_flatten24_mid_fu_735_p2[0:0] === 1'b1) ? ch_2_fu_775_p2 : ch1_mid_fu_703_p3);
assign ch1_mid_fu_703_p3 = ((exitcond_flatten2_fu_697_p2[0:0] === 1'b1) ? ap_const_lv2_0 : ch1_phi_fu_363_p4);
assign ch_1_fu_522_p2 = (ap_const_lv2_1 + ch_phi_fu_283_p4);
assign ch_2_fu_775_p2 = (ap_const_lv2_1 + ch1_mid_fu_703_p3);
assign ch_mid2_fu_552_p3 = ((exitcond_flatten_reg_1239[0:0] === 1'b1) ? ch_1_fu_522_p2 : ch_phi_fu_283_p4);
assign exitcond1_fu_717_p2 = (j3_phi_fu_397_p4 == ap_const_lv3_5? 1'b1: 1'b0);
assign exitcond2_fu_1037_p2 = (j7_phi_fu_466_p4 == ap_const_lv5_14? 1'b1: 1'b0);
assign exitcond3_fu_965_p2 = (filt4_reg_405 == ap_const_lv4_A? 1'b1: 1'b0);
assign exitcond4_mid1_fu_799_p2 = (exitcond4_mid_fu_723_p2 & not_exitcond_flatten24_mid_fu_793_p2);
assign exitcond4_mid_fu_723_p2 = (exitcond1_fu_717_p2 & not_exitcond_flatten1_fu_711_p2);
assign exitcond8_mid_fu_546_p2 = (exitcond_fu_540_p2 & not_exitcond_flatten_fu_535_p2);
assign exitcond_flatten1_fu_490_p2 = (indvar_flatten1_reg_268 == ap_const_lv11_6C0? 1'b1: 1'b0);
assign exitcond_flatten24_mid_fu_735_p2 = (exitcond_flatten3_fu_729_p2 & not_exitcond_flatten1_fu_711_p2);
assign exitcond_flatten24_not_fu_787_p2 = (exitcond_flatten3_fu_729_p2 ^ ap_const_lv1_1);
assign exitcond_flatten2_fu_697_p2 = (indvar_flatten3_reg_348 == ap_const_lv7_4B? 1'b1: 1'b0);
assign exitcond_flatten3_fu_729_p2 = (indvar_flatten4_reg_370 == ap_const_lv6_19? 1'b1: 1'b0);
assign exitcond_flatten4_fu_679_p2 = (indvar_flatten2_reg_326 == ap_const_lv10_2EE? 1'b1: 1'b0);
assign exitcond_flatten5_fu_999_p2 = (indvar_flatten6_reg_439 == ap_const_lv10_190? 1'b1: 1'b0);
assign exitcond_flatten6_fu_987_p2 = (indvar_flatten5_reg_416 == ap_const_lv12_FA0? 1'b1: 1'b0);
assign exitcond_flatten_fu_502_p2 = (indvar_flatten_reg_291 == ap_const_lv10_240? 1'b1: 1'b0);
assign exitcond_fu_540_p2 = (j_phi_fu_318_p4 == ap_const_lv5_18? 1'b1: 1'b0);
assign exitcond_mid_fu_1043_p2 = (exitcond2_fu_1037_p2 & not_exitcond_flatten2_fu_1032_p2);
assign feature_map_d0 = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_d0;
assign filt5_mid2_fu_1049_p3 = ((exitcond_flatten5_reg_1366[0:0] === 1'b1) ? filt_3_fu_1019_p2 : filt5_phi_fu_431_p4);
assign filt_1_fu_971_p2 = (filt4_reg_405 + ap_const_lv4_1);
assign filt_2_fu_691_p2 = (ap_const_lv4_1 + filt_phi_fu_341_p4);
assign filt_3_fu_1019_p2 = (filt5_phi_fu_431_p4 + ap_const_lv4_1);
assign filt_mid2_fu_741_p3 = ((exitcond_flatten2_fu_697_p2[0:0] === 1'b1) ? filt_2_fu_691_p2 : filt_phi_fu_341_p4);
assign filter_d0 = ap_reg_ppstg_reg_486_pp1_it1;
assign grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start = grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_ap_start_ap_start_reg;
assign grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_bias_q0 = bias_q0;
assign grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_feature_map_q0 = feature_map_q0;
assign grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_filter_q0 = filter_q0;
assign grp_Conv_Accel_conv_hw_24_3_10_5_20_s_fu_474_image_r_q0 = image_q0;
assign i2_mid2_fu_901_p3 = ((exitcond4_mid1_reg_1307[0:0] === 1'b1) ? i_2_fu_878_p2 : i2_mid_fu_851_p3);
assign i2_mid_fu_851_p3 = ((tmp_18_reg_1302[0:0] === 1'b1) ? ap_const_lv3_0 : i2_phi_fu_385_p4);
assign i6_mid2_fu_1115_p3 = ((exitcond_mid_fu_1043_p2[0:0] === 1'b1) ? i_3_fu_1096_p2 : i6_mid_fu_1025_p3);
assign i6_mid_fu_1025_p3 = ((exitcond_flatten5_reg_1366[0:0] === 1'b1) ? ap_const_lv5_0 : i6_phi_fu_454_p4);
assign i_1_fu_589_p2 = (ap_const_lv5_1 + i_mid_fu_528_p3);
assign i_2_fu_878_p2 = (ap_const_lv3_1 + i2_mid_fu_851_p3);
assign i_3_fu_1096_p2 = (i6_mid_fu_1025_p3 + ap_const_lv5_1);
assign i_mid2_fu_608_p3 = ((exitcond8_mid_fu_546_p2[0:0] === 1'b1) ? i_1_fu_589_p2 : i_mid_fu_528_p3);
assign i_mid_fu_528_p3 = ((exitcond_flatten_reg_1239[0:0] === 1'b1) ? ap_const_lv5_0 : i_phi_fu_306_p4);
assign image_d0 = ap_reg_ppstg_reg_486_pp0_it1;
assign indvar_flatten22_op_fu_823_p2 = (ap_const_lv6_1 + indvar_flatten4_reg_370);
assign indvar_flatten36_op_fu_837_p2 = (ap_const_lv7_1 + indvar_flatten3_reg_348);
assign indvar_flatten66_op_fu_1005_p2 = (indvar_flatten6_reg_439 + ap_const_lv10_1);
assign indvar_flatten_next1_fu_496_p2 = (indvar_flatten1_reg_268 + ap_const_lv11_1);
assign indvar_flatten_next2_fu_829_p3 = ((tmp_18_fu_781_p2[0:0] === 1'b1) ? ap_const_lv6_1 : indvar_flatten22_op_fu_823_p2);
assign indvar_flatten_next3_fu_843_p3 = ((exitcond_flatten2_fu_697_p2[0:0] === 1'b1) ? ap_const_lv7_1 : indvar_flatten36_op_fu_837_p2);
assign indvar_flatten_next4_fu_685_p2 = (indvar_flatten2_reg_326 + ap_const_lv10_1);
assign indvar_flatten_next5_fu_1011_p3 = ((exitcond_flatten5_fu_999_p2[0:0] === 1'b1) ? ap_const_lv10_1 : indvar_flatten66_op_fu_1005_p2);
assign indvar_flatten_next6_fu_993_p2 = (indvar_flatten5_reg_416 + ap_const_lv12_1);
assign indvar_flatten_next_fu_514_p3 = ((exitcond_flatten_fu_502_p2[0:0] === 1'b1) ? ap_const_lv10_1 : indvar_flatten_op_fu_508_p2);
assign indvar_flatten_op_fu_508_p2 = (ap_const_lv10_1 + indvar_flatten_reg_291);
assign j3_mid2_fu_893_p3 = ((tmp_23_fu_888_p2[0:0] === 1'b1) ? ap_const_lv3_0 : j3_reg_393);
assign j7_cast3_fu_1191_p1 = j7_mid2_reg_1389;
assign j7_mid2_fu_1107_p3 = ((tmp_32_fu_1102_p2[0:0] === 1'b1) ? ap_const_lv5_0 : j7_phi_fu_466_p4);
assign j_1_fu_616_p2 = (ap_const_lv5_1 + j_mid2_fu_600_p3);
assign j_2_fu_950_p2 = (ap_const_lv3_1 + j3_mid2_fu_893_p3);
assign j_3_fu_1133_p2 = (j7_mid2_fu_1107_p3 + ap_const_lv5_1);
assign j_mid2_fu_600_p3 = ((tmp_5_fu_595_p2[0:0] === 1'b1) ? ap_const_lv5_0 : j_phi_fu_318_p4);
assign last_assign_fu_1219_p2 = (tmp_15_fu_1199_p2 == ap_const_lv12_F9F? 1'b1: 1'b0);
assign not_exitcond_flatten1_fu_711_p2 = (exitcond_flatten2_fu_697_p2 ^ ap_const_lv1_1);
assign not_exitcond_flatten24_mid_fu_793_p2 = (exitcond_flatten2_fu_697_p2 | exitcond_flatten24_not_fu_787_p2);
assign not_exitcond_flatten2_fu_1032_p2 = (exitcond_flatten5_reg_1366 ^ ap_const_lv1_1);
assign not_exitcond_flatten_fu_535_p2 = (exitcond_flatten_reg_1239 ^ ap_const_lv1_1);
assign p_shl10_cast_fu_1086_p1 = tmp_30_fu_1078_p3;
assign p_shl11_cast_fu_1157_p3 = {{tmp_33_reg_1402}, {ap_const_lv4_0}};
assign p_shl12_cast_fu_1171_p1 = tmp_34_fu_1164_p3;
assign p_shl1_cast_fu_567_p1 = tmp_1_fu_559_p3;
assign p_shl2_cast_fu_579_p1 = tmp_8_fu_571_p3;
assign p_shl3_cast_fu_646_p3 = {{tmp_6_fu_628_p2}, {ap_const_lv3_0}};
assign p_shl4_cast_fu_761_p1 = tmp_16_fu_753_p3;
assign p_shl5_fu_1139_p3 = {{i6_mid2_reg_1395}, {ap_const_lv4_0}};
assign p_shl6_cast_fu_1153_p1 = p_shl6_fu_1146_p3;
assign p_shl6_fu_1146_p3 = {{i6_mid2_reg_1395}, {ap_const_lv2_0}};
assign p_shl7_fu_868_p1 = $signed(tmp_20_fu_861_p3);
assign p_shl8_cast_fu_926_p3 = {{tmp_26_fu_922_p1}, {ap_const_lv2_0}};
assign p_shl9_cast_fu_1074_p1 = tmp_29_fu_1066_p3;
assign p_shl_cast_fu_638_p3 = {{tmp_9_fu_634_p1}, {ap_const_lv5_0}};
assign tmp1_fu_1194_p2 = (tmp_7_reg_1384 + j7_cast3_fu_1191_p1);
assign tmp_10_fu_908_p1 = i2_mid2_fu_901_p3;
assign tmp_11_cast_fu_1123_p1 = i6_mid2_fu_1115_p3;
assign tmp_11_fu_654_p2 = (p_shl_cast_fu_638_p3 - p_shl3_cast_fu_646_p3);
assign tmp_13_cast_fu_940_p1 = j3_mid2_fu_893_p3;
assign tmp_13_fu_668_p2 = (tmp_5_cast_fu_665_p1 + tmp_11_fu_654_p2);
assign tmp_15_fu_1199_p2 = (tmp1_fu_1194_p2 + tmp_cast_fu_1187_p1);
assign tmp_16_cast_fu_1205_p1 = j7_mid2_reg_1389;
assign tmp_16_fu_753_p3 = {{filt_mid2_fu_741_p3}, {ap_const_lv2_0}};
assign tmp_17_cast_fu_622_p1 = $signed(tmp_3_reg_1257);
assign tmp_17_fu_765_p2 = (p_shl4_cast_fu_761_p1 - tmp_3_cast_fu_749_p1);
assign tmp_18_fu_781_p2 = (exitcond_flatten24_mid_fu_735_p2 | exitcond_flatten2_fu_697_p2);
assign tmp_19_fu_817_p2 = ($signed(tmp_9_cast_fu_813_p1) + $signed(tmp_25_cast_fu_771_p1));
assign tmp_1_fu_559_p3 = {{ch_mid2_fu_552_p3}, {ap_const_lv5_0}};
assign tmp_20_fu_861_p3 = {{tmp_19_reg_1318}, {ap_const_lv2_0}};
assign tmp_21_fu_872_p2 = ($signed(p_shl7_fu_868_p1) + $signed(tmp_27_cast_fu_858_p1));
assign tmp_22_fu_884_p2 = (exitcond4_mid1_reg_1307 | exitcond_flatten24_mid_reg_1292);
assign tmp_23_cast_fu_674_p1 = tmp_13_fu_668_p2;
assign tmp_23_fu_888_p2 = (tmp_22_fu_884_p2 | exitcond_flatten2_reg_1287);
assign tmp_24_fu_912_p2 = (tmp_10_fu_908_p1 + tmp_21_fu_872_p2);
assign tmp_25_cast_fu_771_p1 = $signed(tmp_17_fu_765_p2);
assign tmp_25_fu_918_p1 = tmp_24_fu_912_p2[10:0];
assign tmp_26_fu_922_p1 = tmp_24_fu_912_p2[8:0];
assign tmp_27_cast_fu_858_p1 = $signed(tmp_19_reg_1318);
assign tmp_27_fu_934_p2 = (p_shl8_cast_fu_926_p3 + tmp_25_fu_918_p1);
assign tmp_28_fu_944_p2 = (tmp_13_cast_fu_940_p1 + tmp_27_fu_934_p2);
assign tmp_29_fu_1066_p3 = {{filt5_mid2_fu_1049_p3}, {ap_const_lv4_0}};
assign tmp_30_fu_1078_p3 = {{filt5_mid2_fu_1049_p3}, {ap_const_lv2_0}};
assign tmp_31_fu_1090_p2 = (p_shl9_cast_fu_1074_p1 + p_shl10_cast_fu_1086_p1);
assign tmp_32_fu_1102_p2 = (exitcond_mid_fu_1043_p2 | exitcond_flatten5_reg_1366);
assign tmp_33_fu_1127_p2 = (tmp_11_cast_fu_1123_p1 + tmp_31_fu_1090_p2);
assign tmp_34_cast_fu_961_p1 = tmp_28_reg_1339;
assign tmp_34_fu_1164_p3 = {{tmp_33_reg_1402}, {ap_const_lv2_0}};
assign tmp_35_fu_1175_p2 = (p_shl11_cast_fu_1157_p3 + p_shl12_cast_fu_1171_p1);
assign tmp_36_fu_1208_p2 = (tmp_16_cast_fu_1205_p1 + tmp_35_fu_1175_p2);
assign tmp_3_cast_fu_749_p1 = filt_mid2_fu_741_p3;
assign tmp_3_fu_583_p2 = (p_shl1_cast_fu_567_p1 - p_shl2_cast_fu_579_p1);
assign tmp_44_cast_fu_1214_p1 = tmp_36_fu_1208_p2;
assign tmp_5_cast_fu_665_p1 = j_mid2_reg_1262;
assign tmp_5_fu_595_p2 = (exitcond8_mid_fu_546_p2 | exitcond_flatten_reg_1239);
assign tmp_6_cast_fu_625_p1 = i_mid2_reg_1267;
assign tmp_6_fu_628_p2 = ($signed(tmp_6_cast_fu_625_p1) + $signed(tmp_17_cast_fu_622_p1));
assign tmp_7_fu_1060_p0 = tmp_7_fu_1060_p00;
assign tmp_7_fu_1060_p00 = filt5_mid2_fu_1049_p3;
assign tmp_7_fu_1060_p2 = (tmp_7_fu_1060_p0 * $signed('h190));
assign tmp_8_fu_571_p3 = {{ch_mid2_fu_552_p3}, {ap_const_lv3_0}};
assign tmp_9_cast_fu_813_p1 = ch1_mid2_fu_805_p3;
assign tmp_9_fu_634_p1 = tmp_6_fu_628_p2[6:0];
assign tmp_cast_fu_1187_p1 = tmp_fu_1181_p2;
assign tmp_fu_1181_p2 = (p_shl5_fu_1139_p3 + p_shl6_cast_fu_1153_p1);
assign tmp_s_fu_982_p1 = filt4_reg_405;
always @ (posedge ap_clk) begin
    tmp_3_reg_1257[2:0] <= 3'b000;
    tmp_7_reg_1384[3:0] <= 4'b0000;
end



endmodule //Conv_Accel_wrapped_conv_hw

