// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xconv_accel.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XConv_accel_CfgInitialize(XConv_accel *InstancePtr, XConv_accel_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XConv_accel_Start(XConv_accel *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv_accel_ReadReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XConv_accel_WriteReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XConv_accel_IsDone(XConv_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv_accel_ReadReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XConv_accel_IsIdle(XConv_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv_accel_ReadReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XConv_accel_IsReady(XConv_accel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConv_accel_ReadReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XConv_accel_EnableAutoRestart(XConv_accel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv_accel_WriteReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XConv_accel_DisableAutoRestart(XConv_accel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv_accel_WriteReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XConv_accel_InterruptGlobalEnable(XConv_accel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv_accel_WriteReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_GIE, 1);
}

void XConv_accel_InterruptGlobalDisable(XConv_accel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv_accel_WriteReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_GIE, 0);
}

void XConv_accel_InterruptEnable(XConv_accel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConv_accel_ReadReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_IER);
    XConv_accel_WriteReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XConv_accel_InterruptDisable(XConv_accel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConv_accel_ReadReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_IER);
    XConv_accel_WriteReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XConv_accel_InterruptClear(XConv_accel *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConv_accel_WriteReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XConv_accel_InterruptGetEnabled(XConv_accel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConv_accel_ReadReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_IER);
}

u32 XConv_accel_InterruptGetStatus(XConv_accel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConv_accel_ReadReg(InstancePtr->Control_bus_BaseAddress, XCONV_ACCEL_CONTROL_BUS_ADDR_ISR);
}

