// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XCONV_ACCEL_H
#define XCONV_ACCEL_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xconv_accel_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XConv_accel_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XConv_accel;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XConv_accel_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XConv_accel_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XConv_accel_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XConv_accel_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XConv_accel_Initialize(XConv_accel *InstancePtr, u16 DeviceId);
XConv_accel_Config* XConv_accel_LookupConfig(u16 DeviceId);
int XConv_accel_CfgInitialize(XConv_accel *InstancePtr, XConv_accel_Config *ConfigPtr);
#else
int XConv_accel_Initialize(XConv_accel *InstancePtr, const char* InstanceName);
int XConv_accel_Release(XConv_accel *InstancePtr);
#endif

void XConv_accel_Start(XConv_accel *InstancePtr);
u32 XConv_accel_IsDone(XConv_accel *InstancePtr);
u32 XConv_accel_IsIdle(XConv_accel *InstancePtr);
u32 XConv_accel_IsReady(XConv_accel *InstancePtr);
void XConv_accel_EnableAutoRestart(XConv_accel *InstancePtr);
void XConv_accel_DisableAutoRestart(XConv_accel *InstancePtr);


void XConv_accel_InterruptGlobalEnable(XConv_accel *InstancePtr);
void XConv_accel_InterruptGlobalDisable(XConv_accel *InstancePtr);
void XConv_accel_InterruptEnable(XConv_accel *InstancePtr, u32 Mask);
void XConv_accel_InterruptDisable(XConv_accel *InstancePtr, u32 Mask);
void XConv_accel_InterruptClear(XConv_accel *InstancePtr, u32 Mask);
u32 XConv_accel_InterruptGetEnabled(XConv_accel *InstancePtr);
u32 XConv_accel_InterruptGetStatus(XConv_accel *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
